src/manifest.json, src/scripts/content/taiga.js, src/styles/style.css
Toggl integration for the awesome PM tool Taiga https://github.com/taigaio .
=> Taiga.io support

src/manifest.json, src/scripts/content/habitrpg.js
Pull request adds HabitRPG integration
=> Add HabitRPG integration

README.md, src/manifest.json, src/scripts/content/gemini.js, src/styles/style.css
Gemini on-demand users can now use toggl
=> Added Countersoft Gemini

src/manifest.json, src/scripts/content/esa.js
Add suport for https://esa.io/
=> Add esa.io suport

README.md, src/manifest.json, src/scripts/content/helpscout.js
We added support for use with Help Scout. Our team has tested this internally and it is working smoothly.
=> Helpscout addition

src/scripts/content/taiga.js, src/styles/style.css
Hi, we are improving the taiga integration, we want to improve some styles too, you can wait until we have if you want, or merge it and we make another PR with the styles and other improvements.
=> Improving taiga integration

src/scripts/content/podio.js
=> Add Start/Stop to items in podio

src/scripts/popup.js, src/styles/popup.css
=> make header clickable (open toggl page)

README.md
simple fix for the url of sprintly
=> fix sprintly url

src/scripts/common.js
=> close form instead of reloading website on 'enter'

src/scripts/common.js
=> focus description field on form open

src/scripts/content/taiga.js
With the last release of Taiga the toggl button doesn't work anywhere except on the backlog.
=> Fixing css selectors for taiga.js

src/manifest.json, src/scripts/content/wrike.js
Since my company wants to work with Wrike instead of Trello, I want to contribute to Toggle's button chrome extension
=> Wrike support for toggle-button

src/manifest.json
Because of the recent renaming of HabitRPG to Habitica.
=> Replaced HabitRPG with Habitica

src/manifest.json, src/scripts/content/waffle.io.js
waffle.io is popular work tracking tool on top of github issues
=> Add toggl button to waffle.io

README.md, src/manifest.json, src/scripts/content/codeable.js
Codeable is an online service that brings together prospecting clients with topnotch WordPress professionals. This integration is aimed at the professional contractors at Codeable to better keep track of time of a specific task.
=> added Codeable integration

README.md, src/manifest.json, src/scripts/content/draftin.js
I added a screenshot of where the Toggl button should be at.
=> Added Draftin to this plugin

README.md, src/manifest.json, src/scripts/content/fogbugz.js
Added integration to FogBugz, the project management system created by FogCreek.
=> Added FogBugz Integration

src/scripts/content/gitlab.js
Fix button rendering in new version of gitlab.
=> fix button render in new version of gitlab

README.md, src/manifest.json, src/scripts/content/keep.js, src/styles/style.css
=> Added toggl button to Google Keep

README.md, src/manifest.json, src/scripts/content/devdocs.js
=> Added integration for DevDocs.io

src/html/settings.html, src/manifest.json, src/scripts/background.js, src/scripts/db.js, src/scripts/settings.js
At first i tried setting it with
```
xhr.setRequestHeader('User-Agent', TogglButton.$fullVersion);
```
but chrome would complain about it not being a safe operation. After some research i found this
http://stackoverflow.com/questions/10334909/associate-a-custom-user-agent-to-a-specific-google-chrome-page-tab/10339902#10339902
so that's what i ended up implementing and it works
=> Added custom user-agent header as requested in #487 and added a setting to disable right click button #398

.editorconfig, README.md, src/manifest.json, src/scripts/content/sourcelair.js
This PR adds support for @sourcelair IDE. It supports project name and description.
=> Sourcelair support

README.md, src/manifest.json, src/scripts/content/rememberthemilk.js
This PR add support for Remember The Milk
=> Add Remember The Milk support

src/manifest.json, src/scripts/content/proworkflow.js
Added support for Proworkflow.com
=> Added proworkflow

README.md, src/manifest.json, src/scripts/content/targetprocess.js
Integration with Target Process - a Visual Project Management System
https://www.targetprocess.com/
=> Adding Target Process support

README.md
so, i propose that you do `git merge --squash` when merging pull-requests
then you get:
a) 1 commit in your `master` branch
b) the detailed commits can be still be viewed from pull request
downsides that i see:
* committer may go wrong, but the author should be still reporter
* can't use github webui to do merges, need to click `cli commands` near merge button
=> do git merge --squash

README.md, src/manifest.json, src/scripts/content/smartboard.js
Hi!
SmartBoard is a free Kanban board with lots of features. Toggl integrations allows users to track each task time. After installing the plug-in, tasks will look like the following picture:
In order to create a board and validate the content, please create an account, choose a "freelancer" plan (since it gets automatically accepted), and then click on "New Project".
If any questions arise, please contact me.
Kind regards,
Daniel Merrill
=>  Added smartboard.cl integration

README.md, src/manifest.json, src/scripts/content/phabricator.js
Phabricator is a free software that can be downloaded from phabricator.org or used at phacility.com
=> Add support for Phabricator

src/html/settings.html, src/scripts/background.js, src/scripts/db.js, src/scripts/settings.js
I've noticed PR #495 has remained quiet for 20 days, so i took the liberty of finishing it.
Here is the new setting, the checkbox at the bottom of the image
This is how the notification looks like if the checkbox is not checked
=> Some pomodoro updates taking off from PR #495

README.md, src/manifest.json, src/scripts/content/minicrm.js
Added AgenoCRM, miniCRM support.
=> AgenoCRM and miniCRM integration

src/scripts/content/eventum.js
update integration as mentioned here:
https://github.com/toggl/toggl-button/pull/207#issuecomment-141038193
=> update eventum button integration. #207

src/scripts/background.js
=> fix spelling errors

src/manifest.json, src/scripts/content/habitica.js, src/scripts/origins.js
=> Fix Habitica buttons

src/scripts/content/ticktick.js, src/scripts/origins.js
=> Added TickTick integration

README.md, src/scripts/content/phabricator.js, src/scripts/origins.js
The task view still doesn't work quite right but Phacility works better than before and the version of Phabricator running on Exana is now supported as well.
=> Add exana.io (Phabricator)

src/scripts/content/youtrack.js
=> [YouTrack] Tweak button rendering on the agile board

src/scripts/content/attask.js, src/scripts/origins.js
Hey @IndrekV ,
Here is the Workfront integration adapted to the latest version of Toggl-button.
This replaces PR #559 
Please let me know if you are having trouble getting a trial with Workfront.
Thanks!
Gonen
=> Add Workfront support

README.md, src/scripts/content/onlyoffice.js, src/scripts/origins.js
This commit adds support for onlyoffice.com collaboration software on the Project screen and on the task screen, with subtask support
Main project screen
Task screen and subtask
=> add onlyoffice support

README.md, src/manifest.json, src/scripts/content/meistertask.js, src/scripts/origins.js, src/styles/style.css
Will grab ProjectName, Tags, Description from modal view of MeisterTask
tasks.
=> Meistertask Integration

src/scripts/content/overv.js, src/scripts/origins.js
Add toggl button next to issue title when issue modal is poped-up
=> Overv.io Integration. 

src/scripts/content/eproject.js
Adding Toggl Buttons to the Recent Tasks table on the dashboard and also to the full tasks table.
=> Adding new Toggl Button locations in eProject.me

src/scripts/content/rememberthemilk.js
=> Fix Remember The Milk

README.md, src/scripts/content/clubhouse.js, src/scripts/origins.js, src/styles/style.css
This PR adds support for [Clubhouse](https://clubhouse.io/) project management tool.
=> Add Clubhouse support

src/scripts/content/asana.js, src/styles/style.css
=> Update to Asana

src/html/popup.html, src/scripts/background.js, src/scripts/popup.js, src/styles/popup.css
Show last 5 entries in extension popup for fast continue.
Hovering labels (description, project, tags) shows full text of the label
Hovering an item in the list revels the continue button.
=> Added recent time entries list to popup

README.md, src/scripts/content/teamleader.js, src/scripts/origins.json, src/styles/style.css
You can find the toggl link in every widget.
=> Add teamleader support.

README.md, src/scripts/content/intercom.js, src/scripts/origins.json, src/styles/style.css
The Toggl button will appear at the top right corner of the input form. The `description` attribute is set to the message that is received in Intercom.
=> Added support for Intercom

src/scripts/content/github.js
Need to be a bit more aggressive when listening to DOM changes in
github.
closes #755
=> Fix button in github

src/scripts/autocomplete.js, src/scripts/background.js, src/scripts/common.js, src/scripts/popup.js, src/styles/autocomplete.css
I'm not sure if we should filter by the default workspace when there is no project selected. Any inputs?
closes #700
=> Filter tags by ws when there's a selected project

src/scripts/content/zube.js
=> Fix zube.io

src/scripts/content/salesforce.js, src/scripts/db.js, src/scripts/origins.json, src/styles/style.css
=> Fix salesforce permission and button placement

src/scripts/content/rememberthemilk.js
=> Fixed button missing on Remember The Milk (RTM)

src/scripts/background.js, src/scripts/popup.js, src/styles/autocomplete.css
So we don't conflict with other page styles
I couldn't find any refrence to `color-x` classes. Probably safe to remove. I think it should've been removed here:
https://github.com/toggl/toggl-button/commit/f46081443e82ee87713b72b85b12987907693d4e
Thoughts?
Closes #779
=> Add namespace to CSS styles

src/scripts/content/bitbucket.js
- Get the correct project name from Bitbucket
- Remove whitespace from pull request description (fixes #789)
=> Get the correct project name from Bitbucket

README.md, src/scripts/content/processwire.js, src/scripts/origins.json, src/styles/style.css
You guys can test the extension at the demo of ProcessWire's new theme at [http://demo.processwire.com/regular/processwire](http://demo.processwire.com/regular/processwire)/. You can login with username _bloguser_ and password _processwire3_
=> Added ProcessWire integration

src/scripts/background.js
Immediately updates visual progress for entries when the Pomodoro Timer is enabled.
Closes #802.
=> Update Pomodoro progress immediately

src/scripts/content/openproject.js, src/styles/style.css
OpenProject 7.0 has plenty of changes in the DOM and was already launched in the Saas environment on openproject.com. Official stable packages will be released in a matter of days.
This PR adopts scripts and styles to the new DOM.
=> Update scripts and styles for OpenProject 7.0

README.md, src/scripts/content/khanacademy.js, src/scripts/origins.json, src/styles/style.css
The previous PR #798 can't be merged because of reasons so I moved the code here. All of this code was written by @Phenome.
=> Add Khan Academy integration

README.md, src/scripts/content/husky-marketing-planner.js, src/scripts/origins.json
Integration for [Husky Marketing Planner](https://www.huskymarketingplanner.com)
=> Husky Marketing Planner integration

src/scripts/content/youtrack.js
They've updated the agile board view. Fixed.
closes #760
=> Fix agile board view in YouTrack

README.md, src/scripts/content/nozbe.js, src/scripts/origins.json, src/styles/style.css
Button is visible in the details panel after selecting a specific task. http://i.imgur.com/hVnBDuE.png
=> Added Nozbe integration

src/scripts/origins.json
Turns out it was just listed under the wrong name. 🙈 
closes #834
=> Fix YouTrack integration name

src/scripts/content/google-calendar.js, src/styles/style.css
Solve to https://github.com/toggl/toggl-button/issues/544
=> GoogleCalendar fix, now works with tasks and goals

src/html/popup.html, src/styles/popup.css
=> Add "sign up" option to login form

src/scripts/background.js
It was simply never fetched from localStorage.
closes #856
=> Fix global default project

src/scripts/content/toodledo.js
I don't know what kind of sorcery they're doing with their UI, but it's causing the button to be placed again every time you check/uncheck a task in Grid View. Fixed it by adding a check. 
About the Multi-line view, the UI was probably updated. (fixed) /shrug
closes #846
=> Fix Toodledo integration

README.md, src/scripts/content/codebase.js, src/scripts/origins.json, src/styles/style.css
Toggl button integration for [Codebase](https://www.codebasehq.com). [#740](https://github.com/toggl/toggl-button/issues/740)
Can be used from Tickets (issues) & Merge Requests pages. 
- Matches the titles of respective pages as the Timer Description & Codebase project name as Timer Project
Here's a screenshot on Tickets page --
And, here's one on the Merge Requests page --
`make lint` has passed & submitted in 1 commit.
=> Add Codebase integration

src/scripts/content/asana.js
A selector got updated causing the integration to break.
closes #842
=> Fix asana integration

README.md, src/scripts/content/rallydev.js, src/scripts/origins.json, src/styles/style.css
Add integration to [RallyDev](https://rally1.rallydev.com), so we could measure time for tasks/userstories:
* ![image](https://user-images.githubusercontent.com/7689103/28943734-25d9d74a-78a0-11e7-8a5b-559eff9299ec.png)
* ![image](https://user-images.githubusercontent.com/7689103/28943827-809e0b9c-78a0-11e7-8be5-da5a6238e05b.png)
CC: @syko
=> Add RallyDev integration

src/scripts/content/gitlab.js
Hi.
I fixed gitlab button in #877, but gitlab design re-changed yesterday.
So not working now. ( #884 )
I fix that, again.
Issue page
MR page
Thank you.
=> Fix gitlab button for new design

README.md, src/scripts/content/rollbar.js, src/scripts/content/visualstudio.js, src/scripts/content/zube.js, src/scripts/origins.json, src/styles/style.css
PR for integrating [Rollbar](https://rollbar.com), a real-time error tracking & debugging tool for developers. It's free & really easy to set up for any project. 
- The name of the error/issue is the Timer Description & the Rollbar project name is Timer project.
Individual error tracking page - 
Passed `make lint`. Thanks.
=> Add Rollbar integration & Fix toggl button not appearing issue on Zube & VisualStudio

src/scripts/content/youtrack.js
Eliminates the different behavior of the timer on the agile board and the task card
=> Fix. Add task id for agile board of Youtrack

src/scripts/content/gitlab.js
I re-write for old gitlab button ( https://github.com/toggl/toggl-button/issues/886#issuecomment-330759662 ).
I think, it work at both gitlab (new and old two themes).
But I cannot test about old gitlab.
If somebody test it, please check this PR.
Or don't, please close this.
=> Fix gitlab button for old design

src/scripts/content/teamweek.js, src/styles/style.css
Changes were needed due to new task form design in Teamweek
=> Fix Teamweek integration

src/scripts/content/gitlab.js, src/styles/style.css
=> Fix button position in Gitlab

src/scripts/content/atlassian.js, src/styles/style.css
=> Fix button in JIRA boards

README.md, src/scripts/content/versionone.js, src/scripts/origins.json
=> add VersionOne integration

src/scripts/content/visualstudio.js
It is very useful to have the id of the work item in the toggl description.
In this way, when we start the timer, the description will have this format: "[xxxyyy] - workitem title"
=> Add work item ID in Toggl description

src/scripts/content/asana.js, src/styles/style.css
Fix asana task view
Fix asana board modal task view
Attaching screenshots of all asana integrations
Closes #1020
=> Fix Asana selectors

src/scripts/content/asana.js, src/styles/style.css
Apparently Asana is slowly rolling out UI changes and the recent fix actually broke the UI for people without the newest stuff.
=> Fix the older new Asana UI

src/scripts/content/targetprocess.js
Base version from [here](https://github.com/toggl/toggl-button/pull/1017)
Closes #1010 
* Fixes targetprocess integration thanks to @S3ns3o 
* Some cleanup
Documenting the integration locations here
* Tasks in table view
* Main entity view
* Entity's task view
=> Fix target process integration

src/scripts/content/targetprocess.js
Hello,
A little fix consisting in trying both version of TargetProcess Gui to generate the button.
This could respond to  #1010.
=> Fix targetProcess new gui version + add some crash protection

src/scripts/content/capsulecrm.js
Update the class selectors used in the Capsule integration to reflect changes in Capsule.
=> Fix Capsule CRM integration

src/scripts/content/todoist.js
=> Fixing #897 doesn't input project name automatically in Todoist

src/scripts/autocomplete.js, src/styles/autocomplete.css
Adds nice keyboard support to project autocomplete. 
It's possible to:
- move UP/DOWN
- show/hide tasklist with LEFT/RIGHT
- Select project or project and task with ENTER
=> Project autocomplete keyboard support

src/scripts/content/teamweek.js
=> Fix button integration for tw task popup

src/html/popup.html, src/scripts/background.js, src/scripts/popup.js, src/styles/popup.css
Closes #841 
* Add a view for creating a new workspace
* Show validation error if no workspace name is entered
* Show create workspace prompt if a workspace is removed on sync
* Show create workspace prompt if a timer from a revoked workspace is resumed
1. Starting with two toggl accounts (a, b)
2. Create a workspace with one account (a) and invite the other account (b)
3. Open the popup once after being added to the workspace (and accepting the invitation) so that sync is called an the button knows of the new workspace
4. Now deactivate or delete account b from a's workspace
5. Open the popup again this time you should be prompted to create a workspace
=> Handle workspaces empty state

.gitignore, src/scripts/content/atlassian.js, src/scripts/content/bitbucket.js
Added Bitbucket Server support for version 5.9.0
Added JIRA Server support for getting the project element.
Trimmed the Confluence description.
=> Added Bitbucket Server support for version 5.9.0

README.md, src/scripts/content/workast.js, src/scripts/origins.json, src/styles/style.css
- Toggl button appears in task lists
- Toggl button appears in subtasks
- Toggl button does not appear on lists of completed tasks
- Project is taken from the title of the list in which the task appears (this can be inconsistent between different organizing pages)
=> Added workast integration

src/scripts/content/ticktick.js
This is a fix for issue #1044.
=> fix the inclusion of placeholder text on ticktick.com

README.md, src/scripts/content/vivifyscrum.js, src/scripts/origins.json
=> VivifyScrum integration

src/scripts/content/outlook.js, src/scripts/origins.json, src/styles/style.css
Other people meeting preview:
Other people event details:
My event preview:
=> Office.com calendar Integration

src/scripts/content/helpscout.js
Fix Help Scout integration as mentioned in #1094 
- Go to Help Scout (demo mailbox is enough)
- Button should be visible in minimal state
=> Fix Help Scout integration

package.json, src/chrome-manifest.json, src/firefox-manifest.json, webpack.config.js
Use one package version field for all manifests.
=> Use package version in manifests

src/scripts/popup.js
Fixes continuing time entries in list sometimes triggering the workspace create view.
Closes #1110.
=> Fix continuing time entries in list

src/scripts/content/intercom.js, src/styles/style.css
Login to Intercom, view conversations, button should be displayed as following:
=> Fix Intercom support

src/scripts/content/google-keep.js, src/styles/style.css
Fix Google keep tags list
- Go to Google keep, add some `#tags` and verify if timer works.
Close #1082
=> Fix Google keep integration

src/scripts/content/toggl.js
=> Fix process undefined in content script

src/scripts/content/evernote.js, src/styles/style.css
Update Evernote support.
For testing purposes you need to switch to new Evernote layout which can be done from Evernote profile menu
close #1126
=> Add support for new Evernote layout

src/styles/autocomplete.css, src/styles/style.css
Set some color in new Time Entry popup. Fixes Todoist dark mode integration
close #1134
Check some other integrations than Todoist dark mode too 👀
=> Fix Todoist dark mode integration

src/html/settings.html, src/scripts/lib/db.js, src/scripts/settings.js, src/styles/settings.css
This improves the settings display on Chrome and Firefox, fixing a lot of issues a long the way #1115, and simplifies related styles and behavior to make it easier to add more tabs in the future. 
Please try out the development build on both Chrome and FF and make sure things are indeed looking a lot more like they were supposed to :+1:!
=> Improve settings view

package-lock.json, package.json, src/scripts/lib/ga.js
=> Use nanoid for UUID generation

src/scripts/settings.js
Fix setting default project. 
* Pull this branch
* Go to extensions settings
* Select default project
* Start timer, see that project is attached to time entry
close #1119
=> Fix setting default project

package-lock.json, package.json
Upgrades Babel packages and adds support for optional chaining syntax.
=> Add Babel support for optional chaining

src/html/settings.html, src/scripts/background.js, src/scripts/lib/db.js, src/scripts/settings.js
Adds a note about telemetry settings to the intial popup shown on the settings page.
=> Add note about telemetry settings description to initial settings popup

src/scripts/settings.js, src/styles/settings.css
Please re-add the add-on and confirm the settings guides are nicely centered :+1:!
Fixes #1163.
=> Fix guide container positioning

src/scripts/settings.js
We have a wildcard permission in Firefox, so the permissions tab is redundant.
It's possible to implement for Firefox, but requires some additional work around origin permissions. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/request
So we are hiding the permissions tab for now to reduce confusion, because it simply doesn't do anything in Firefox yet. The plan is to revisit this after resolving some more critical issues first. Part of #1060.
* Do not show Permissions tab link and tab content in Firefox
* Do not show Permissions instructional popup on Firefox
* Add a check when loading the active tab from local storage in Firefox, as there is one fewer tab now and there is a possibility of an error.
* Remove/clean up some conditional Firefox code in …
=> Hide permissions tab in Firefox

README.md, src/scripts/content/reviewboard.js, src/scripts/origins.js, src/styles/style.css
=> Add Reviewboard Integration

src/scripts/content/visualstudio.js, src/scripts/origins.js
Update Visual Studio Team Services integration. 
Please check both old and new layout, you can read more about switching between those two [here](https://blogs.msdn.microsoft.com/devops/2018/06/19/new-navigation/)
=> Handle new navigation layout for Visual Studio Team Services

src/scripts/content/todoist.js
- simplified project name resolution
- tag support
=> Improved Todoist Integration

src/scripts/content/podio.js
=> Trim description text in Podio integration

src/scripts/content/anydo.js, src/scripts/origins.js, src/styles/style.css
Button is displayed for tasks and subtasks:
close #1166
=> Update Any.do integration

src/scripts/settings.js, src/styles/settings.css
Fix broken layout in a filtered list and the clear button:
Fix permission search sometimes not updating with a small refactor. Fixes #835 .
Please check both Chrome and Firefox. Bonus points if you're not on macOS.
=> Fix some low hanging Settings issues

src/scripts/common.js
=> Prevent keydown event bubbling when inside toggl popup

src/html/popup.html
Improves our insights for traffic. Checked with traffic in Slack.
=> Add utm parameters to sign up link

src/scripts/content/bitrix24.js
Fix selectors for new UI, and add support for tags.
I ran it through linting as well.
Closes #899.
=> Fix/rewrite Bitrix24 integration

README.md, package-lock.json, src/scripts/content/produck.js, src/scripts/origins.js, src/styles/style.css
This PR adds Toggl button integration for Produck issue details modal. As discussed with Jake, we are still on private alpha and we need to have this approve to pitch potential customers. This is a screencast of its functionality: http://recordit.co/xdioRH82m2
The product name is `Produck`
Thanks,
Juan
=> Add produck integration

src/scripts/content/freshdesk.js
Adds back in the ticket number with the same format as old code. `{ID} {SUBJECT}`
Works as expected, doesn't break when navigating between tasks or back to "All tickets", etc.
Fixes #1236.
=> Include ticket number in Freshdesk Mint description

src/scripts/content/xero.js, src/scripts/origins.js
Xero changed UI.
This fixing show button in the list.
Fixed #1059
=> Fix xero button

src/scripts/content/github.js
Add Button in GitHub Project sidebar
Test Chrome and Firefox.
resolve #1057
=> Add GitHub Project button

src/scripts/background.js
Resolves a syntax error that can break Firefox extension. Chrome seemed to handle it without issue. Something might be up with babel here.
Possible related to #1263, but I don't think this causes problems in Chrome so probably not.
=> Fix invalid assignment in createTimerLink

.eslintrc.js, .github/CONTRIBUTING.md, .gitignore, .travis.yml, package-lock.json, package.json, src/scripts/background.js, src/scripts/common.js, src/scripts/popup.js, src/scripts/settings.js
* Add eslint config. Pulled in some custom config from other projects. Tried to limit globals config to their individual files to make future reasoning easier.
* Lint changed files in Travis CI
* 🚨 Lint/reformat core script files
* Banish `xo`
Example of failing build in CI if errors crept through: https://travis-ci.org/toggl/toggl-button/builds/483856994
We should verify the reformatted scripts have not somehow broken.
=> Tooling: Add linting

src/scripts/background.js
Send login and fetch errors to bugsnag. Included the status code in the error message as I'm not sure metaData can be filtered/reported on with our service plan.
To assist diagnosing any login or startup sync issues.
seems good
=> Send login and fetch errors to bugsnag

src/scripts/content/salesforce.js, src/styles/style.css
- Partly reverts 0b60bdc
- Restores salesforce legacy integration
- Use Salesforce Legacy (non-lightning view)
- Button should be visible
Closes #1303 
https://toggl.slack.com/archives/C9LMUPD9T/p1550092813031200
=> Restore Salesforce Legacy integration

src/scripts/background.js, src/scripts/common.js, src/scripts/content/todoist.js
This PR makes some changes to `common.js`, along with minimal changes to `todoist.js` in order to mostly resolve the performance issues described in https://github.com/toggl/toggl-button/issues/1275
* Extracts out a function called `queryAndUpdateTimerLink` (better name suggestions appreciated).
* `queryAndUpdateTimerLink` is now run at the end of `renderTo` instead of at the end of `createTimerLink`. 
- Here's why:  Code similar to `queryAndUpdateTimerLink` was being run after every single `createTimerLink` invocation.  This was tremendously inefficient, because it sends a message to the toggl-button background page asking it to say what the currently tracked task is.  The handler for every response to these calls would then scan every single link and modify it via activate / deactivate. …
=> Improve performance for pages with many toggl buttons + cleanups + todoist performance improvements

src/scripts/content/freshdesk.js
This prevents any extra controls in the UI being included in the TE description. Fixes #1323.
This happens for "Portal" tickets. Example: https://togglbutton.freshdesk.com/a/tickets/10
Fixes #1323.
=> Freshdesk: remove child elements from subject

package-lock.json, package.json, src/scripts/background.js, src/scripts/lib/bugsnag.js, webpack.config.js
Refactor Webpack build for source mapping
- Build all content scripts in webpack instead of copying files
- Build scripts to _one_ place, then later copy to separate chrome and firefox directories for ease of archiving etc.
- Transform file names in Bugsnag:beforeSend to one consistent format
- Use Bugsnag sourcemap plugin to upload source maps
- Delete sourcemaps before archiving
TBD
TBD
=> Generate source maps for error reporting

webpack.config.js
=> Fix bugsnag sourcemap tool not receiving key

src/scripts/lib/db.js
Closes #1360
- Pass correct defaults to `get` method
- Use origins from `this.get` instead of global origins directly
- Fix file name calculation in `getOriginFileName` 
- Enable a few integrations
- They should work correctly
- Check custom domain integrations
- Check that `any.do` works, as it uses a subdomain which operates a little differently
Closes #1360
=> Hotfix for origins not begin fetched

README.md, src/scripts/content/focuster.js, src/scripts/origins.js
This PR adds support for toggle button @ focuster.com 
It will show the toggle button on the planning view and the now screen
=> Adds support for focuster.com

src/html/popup.html, src/scripts/background.js, src/scripts/popup.js
This removes a click, streamlining the flow.
Regardless of your `show post start popup` setting, when continuing an entry from the list you will not see the edit form appear.
Closes #1369.
=> Do not show edit form when continuing an entry

package-lock.json, package.json, src/scripts/components/Timer.tsx
Allows pressing `ENTER` in timer bar to start new timer.
The timer behaves as before, while now being able to press `ENTER` to start it while the description field is focused.
Closes #1372.
=> Enable starting new timer with "enter" in the timer form

README.md, src/scripts/common.js, src/scripts/content/workflowy.js, src/scripts/origins.js, src/styles/style.css
Adds the toggl button to [workflowy.com](https://workflowy.com/) in two places.
In the hover popup:
In the more options menu:
1. Navigated to [workflowy.com](https://workflowy.com/).
2. Created a bullet.
3. Hovered over the bullet (the circle part).
4. Observed how the toggl button appeared. (pass)
1. Navigated to [workflowy.com](https://workflowy.com/).
2. Created a bullet.
3. Clicked on the bullet (the circle part). This makes it so that that bullet is now the top bullet.
4. Clicked the more options menu on the right.
5. Observed how the toggl button appeared. (pass).
The field selectors traverse the DOM to grab the description & tags, and because of how …
=> feat: Added workflowy.com integration

src/scripts/components/Timer.tsx
fix: Fix timer description pushing buttons buttons out of view
Closes #1381.
=> fix: Fix timer description pushing buttons buttons out of view

src/scripts/background.js
This had broken due to an oversight with an async change to a function. Fixes #1383.
Didn't change or rewrite any functionality, just fixed the broken-ness and renamed a function.
1. Set up "Remind me to track time" with some work hours that `now` does not fall into. Probably set the "After x minutes" to 1 minute.
2. Start and stop a TE. Now wait for a minute.
3. You will see logs in the background console, but no notification, because we are not within the work hours limits you set.
Inversely, it should show a notification when we **are** within the set work hours limits,.
Fixes #1383.
=> fix: Fix tracking reminder not respecting working hours

src/scripts/content/wrike.js, src/styles/style.css
This adds further information to the description (wrike issue number) as well as the project name (folder / project name) to the toggle button integration.
=> Wrike: Extract project name and issue number

src/scripts/background.js
🚨 **Depends on the PRs in other projects before deploy**.
Part of #1293.
Install the dev extension, them remove it. You should see the uninstall page URL opened in a tab (it'll probably `404` as it is not live yet).
Part of #1293.
=> feat: Set uninstall URL to feedback page

package-lock.json, package.json, src/images/baseline-arrow_drop_down-24px.svg, src/images/baseline-close-24px.svg, src/scripts/@toggl/time-format-utils/index.js, src/scripts/background.js, src/scripts/common.js, src/scripts/components/Timer.tsx, src/scripts/lib/autocomplete.js, src/scripts/lib/timerUtils.js, src/scripts/popup.js, src/styles/autocomplete.css, src/styles/edit-form.css, src/styles/popup.css, src/styles/style.css
Updates the appearance/layout of:
* "Edit TE" screen (when clicking on running TE in the toolbar pop up)
* "Timer popup" pop up when you start a timer in an integration
Adds new features:
* When changing the duration in "Edit TE" screen, you may now use `human inputs` in the same way as webapp. **Probably some minor glitches here, please test.**
Known things that won't be fixed:
* Would love to change the tags popdown to be a list (like webapp) and show selected tags at the start, but we're out of time. Will make a feature out of it in future.
* I have noticed that text rendering seems to get butchered slightly in the Chrome browser popup *(compare: open …
=> Best effort new edit forms / timer popup

src/styles/autocomplete.css, src/styles/edit-form.css
=> Fix long project names breaking task layout

src/scripts/background.js
Fix possible type error when fetching user time entries. [bugsnag](https://app.bugsnag.com/toggl-dot-com/toggl-button/errors/5cadc2aaecd6cc001bbf6b9f?filters[event.since][0]=30d&filters[error.status][0]=open)
[bugsnag](https://app.bugsnag.com/toggl-dot-com/toggl-button/errors/5cadc2aaecd6cc001bbf6b9f?filters[event.since][0]=30d&filters[error.status][0]=open)
=> Fix possible type error when fetching user time entries

src/scripts/content/youtrack.js, src/styles/style.css
Closes #1364
Fix agile board buttons in YouTrack
Closes #1364.
=> Fix agile board buttons in YouTrack

src/scripts/content/rememberthemilk.js, src/styles/style.css
Simplify the code a little, to fix:
1. Script errors seen in error reporting
2. Conform to the styleguide for lists of buttons
3. Also fixes a CSS issue that can affect many integrations, see #1415 
=> Refactor/fix: remember the milk

src/scripts/content/fibery.js, src/scripts/origins.js, src/styles/style.css
Add integration to fibery.io, a work management platform by targetprocess
closes #1411
=> feat(fibery): Fibery Integration

src/scripts/background.js
- Continuation of #1452 
- Trigger notification even if user is in idle state
- Refactor some code
Closes #1444
=> Always trigger idle notification after time delta

.travis.yml, package-lock.json, package.json, src/scripts/content/intercom.js, src/styles/style.css
Fix CI build by updating node version (Travis wants to run `npm ci`, doesn't exist in 8.x) and updating package-lock via an install.
Fix intercom button not appearing in conversation.
Known issue: as soon as you do something in this reply area of the UI, the button will no longer look like it is running. I don't know if this is some edge case in whatever rendering code, or if the fact that Intercom UI appears to update the DOM here a lot, we simply can't avoid it for the timebeing. Or without doing some hack like rendering it elsewhere and positioning it absolutely/fixed.
Test in a test conversation, such …
=> Fix Intercom conversations integration, Fix CI

src/scripts/content/todoist.js
The container used for performance improvements was being replaced when changing projects. Change to use a higher up container (for the right side of the app) which is not replaced.
Switch between projects and see that the buttons are freshly rendered and working correctly 🙏 
Fixes #1462.
=> fix(todoist): Fix Todoist integration breaking when switching between projects

src/scripts/common.js, src/scripts/content/trello.js
* Fixes Trello integration. Some subtle UI updates had broken it.
* Make it not completely error out if the UI has changed again. We'll still of course hear about it not pulling in information if it breaks, but at least it will function.
Please take care that it does work for all cards, and checklist items. Use the `Toggl Button Project` project.
Closes #1476 and closes #1449
=> fix(trello): Fix Trello integration after UI updates

src/scripts/content/slack.js, src/styles/style.css
Fix both places where the button should show up:
1. at the top next to the channel name
2. next to the buttons that show up when you hover messages
1. Load extension
2. Enable Slack in the permissions settings
3. Go to https://toggl.slack.com or any other Slack account
4. Make sure the button shows up at the top next to the channel name
5. Make sure it is showing up when you hover messages 
👍 
closes #1477
=> fix(slack): Fix slack integration after UI updates

src/scripts/content/teamweek.js, src/styles/style.css
Fixes broken Teamweek integration after document structure changes
Button should appear in task view 
Closes #1455
=> fix(teamweek): Fix broken integration

src/scripts/content/outlook.js, src/styles/style.css
- 69e77ac - **fix(outlook): Fix Outlook integration**
- Open Outlook
- Go to "New Message" and the timer button should be there
- Go to a message in the inbox, and the timer button should be there
Related #1484
=> fix(outlook): Fix Outlook integration

README.md, src/scripts/content/dynamics-365.js, src/scripts/content/dynamics365.js, src/scripts/origins.js
Integration of Dynamics 365 Customer Engagement. It is visible on every entry when using the Unified Interface. On the Entry **Case** Case No. and Customer will be transferred to Toggle.
#921 _Suggestion: Add to Case Page on Dynamics CRM/Dynamics 365_
=> feat: Add Dynamics 365 integration

README.md, package-lock.json, src/scripts/content/google-classroom.js, src/scripts/origins.js, src/styles/style.css
Add a simple integration for Google Classroom.
Unfortunately it has a (probably unmaintainable) weird CSS selector but I couldn't think of a better way to select that element.
Closes #1129
=> feat(google-classroom): new integration

src/scripts/content/todoist.js, src/styles/style.css
- Support new Todoist UI
- Drop support for old UI
- Simplify project name detection
- Open Todoist (new UI is rolled to everyone)
- Button should render in actions list on the right of a task
Closes #1521
=> Support new Todoist Foundations interface

src/scripts/content/asana.js, src/styles/style.css
- 0d9dc8b  - **feat(asana): Support new Asana UI (in beta)**
Spreadsheet view should be good (including clicking on a task in detail):
https://app.asana.com/0/729617904817453/list
Older task lists should be good (including clicking on a task in detail):
https://app.asana.com/0/729616262525591/list
- Check if toggl button it's working correctly on the new Asana UI
- All changes should be tested across Chrome and Firefox.
Related #1508
=> feat(asana): Support new Asana UI (in beta)

README.md
Improves the introduction in the `README` with shields that display the information about the latest Chrome and Firefox releases and re-uses copy from https://toggl.com/toggl-button/.
Check `README` preview.
See: https://toggl.com/toggl-button/
=> docs(README): Add status shields and new copy to README

src/scripts/components/LoginPage.tsx
- Should help for easy discovery and aggregation in bugsnag
- Manually force an error on login page (change default error state to some string)
- It should be reported to bugsnag with the context
Closes #1545
=> Track login errors

src/scripts/content/ticktick.js
- Updates integrations to support new TickTick UI
- Verify if button appears in the task info sidepanel on TickTick
Closes #1514
=> Add support for new TickTick UI

src/scripts/content/anydo.js
Gets the correct task description from Any.do's task list.
Track an item from the task list and check the correct description is used.
Closes #1551 
Also closes #1553
=> fix(any.do): Update description and project selectors

src/scripts/background.js, src/scripts/common.js, src/scripts/lib/autocomplete.js
- 0c0a6e5 - **fix(popup): Fix tag/project dropdown toggle in-page**
Similar fix to d40b843, but this time for the dropdown in-page
- Check if tab/project popdowns in the extension works fine. Inside integrations (e.g. Trello) as well as from the main toolbar popup.
Related #1422
=> fix(popup): Fix tag/project dropdown toggle in-page

src/scripts/background.js
Precaution for stability issues while we investigate
If you close it, it never reconnects automatically.
=> chore(websocket): Disable retries

src/scripts/background.js
- Max limit is an hour
- No limits on retries
=> Implement exponential backoff

src/scripts/components/TimeEntriesList.tsx, src/scripts/components/Timer.tsx, src/scripts/popup.js
- Adds click to expand TE group functionality
- Click a time-entry group
- Child time-entries should be rendered
- Clicking on TE group should not open Edit View
- Clicking on child TEs should open the Edit View
Closes #1579
=> Allow expanding of TE groups

src/scripts/background.js, src/scripts/popup.js
- Allow editing of stopped entries
- Brings TE editing of stopped entries to feature parity with running entries
- Open popup
- Try editing some time entries
- Try editing both stopped and active entry
Please merge #1578 and #1580 before reviewing this
Closes #1582
=> Update TE on using Edit Form

src/scripts/background.js, src/scripts/common.js, src/scripts/components/TimeEntriesList.tsx, src/scripts/components/Timer.tsx, src/scripts/popup.js, src/styles/edit-form.css
- Adds support for editing stopped entries
- Support for changing start/stop time will come in a later release
- Changes have already been tested in smaller PRs #1578, #1580 and #1582 
- So just verifiy if the Edit form works well and editing running and stopped entries works as expected
Closes #1564 
Closes #1565 
Closes #1579
=> Phoenix release 1: Add support for editing stopped entries

src/scripts/background.js
- Pass active TE id instead of `undefined` in API call
- Fixes TEs not being updated on using the edit form in integrations.
- Open the background script console
- Start an integrated entry
- On making changes and pressing Done the Network request tab should show correct update
- On master the endpoint used has `undefined` instead of time-entry id
Closes #1596
=> Fix TE update changes being ignored

src/html/settings.html, src/scripts/settings.js, src/styles/settings.css
Updates the Toggl Button settings page to look like the Toggl web app.
Dark mode:
Open the settings page, turn settings on and off.
Closes #1571
=> Update settings page

src/scripts/background.js, src/scripts/popup.js, src/styles/edit-form.css, src/styles/popup.css
Add delete functionality to the edit entry form.
- Delete a completed entry
- Delete a running entry
Closes #1583
=> feat(popup): Delete time entries

src/scripts/content/worksection.js, src/styles/style.css
Adds support for new Worksection layout. Fixes integration 🤷‍♂ 
Button should be visible in few places:
_to view it you need to click on item in tasks list (BUT NOT ON TITLE 💥)_
Closes #1496
=> Add support for new Worksection layout

src/scripts/@toggl/time-format-utils/format-duration.ts, src/scripts/components/Summary.tsx, src/scripts/components/TagsIcon.tsx, src/scripts/components/TimeEntriesList.tsx, src/scripts/components/Timer.tsx, src/scripts/icons/play-green.svg, src/scripts/icons/play.svg, src/scripts/lib/groupUtils.ts, src/scripts/popup.js, src/styles/popup.css
Make the time entry list look more like the Mac desktop design
Use the popup
=> Update time entry list styles

src/html/settings.html, src/scripts/settings.js, src/styles/settings.css
Refreshing and going back/forward now work for settings pages.
Initially I just added `history.pushState` but back/forward didn't work since the page isn't reloading, so I changed the menu to use normal links instead.
Browse through the settings pages, refresh, go back and forward.
Suggested by @tcrammond in #1600
=> Settings - remember tab

src/scripts/content/zenhub.js, src/scripts/origins.js, src/styles/style.css
Adds the timer integration to issues and PRs in the project management tool [zenhub.com](https://zenhub.com).
None
=> feat: Add ZenHub integration

src/html/settings.html, src/scripts/components/TimeEntriesList.tsx, src/styles/settings.css
Fixes two visual bugs
1. Text on the review button not being centred
Before:
After:
2. Description and duration on the new entry style not lining up
Before:
After:
Check appearance of both on PR3 and this branch
=> Style fixes for Phoenix Release 3

src/scripts/content/asana.js
Fixes button not showing up on Asana's new detail view
Button should show up here and work as expected:
Closes #1631, #1633 and #1634
=> fix(asana): Fix Asana detail view

src/scripts/background.js, src/scripts/common.js, src/scripts/content/atlassian.js
Fixes project and tag dropdowns not working in this issue view:
*NOTE*: still need to fix input fields not being usable on the popup (description, project filter, tag filter) (#1448) - not sure what's happening here
Start a timer from the JIRA issue popup. ([link to our test board](https://togglbutton.atlassian.net/jira/software/projects/NGSP/boards/3?selectedIssue=NGSP-2))
Closes #1448 
Closes #1623
=> fix dropdowns not appearing in JIRA popup issue view

README.md
Eventum uses GitHub for its project management: https://github.com/eventum/eventum
=> readme: update eventum url

README.md
Add Notion to the Readme.
Check if the link works.
Added in https://github.com/toggl/toggl-button/pull/1203, fixed in https://github.com/toggl/toggl-button/pull/1612 and https://github.com/toggl/toggl-button/pull/1617
=> chore(readme): Add Notion to README

README.md, src/scripts/content/helprace.js, src/scripts/origins.js
We added support for use with Helprace. Our team has tested this internally and it is work.
=> feat(helprace): Add Helprace integration

src/scripts/content/gitlab.js
GitLab: Add GitLab labels as Toggl Tags. Requires GitLab 12.7
- https://github.com/toggl/toggl-button/issues/1657
=> GitLab: Add GitLab labels as Toggl Tags

src/scripts/content/ticktick.js
Fix TickTick not filling in timer description
Description is picked up
Fixes #1670.
=> fix(ticktick): Fix TickTick not filling in timer description

src/scripts/content/zendesk.js
Fix the title selector of the Zendesk integration
I've added an account for testing purposes to the credentials file (Zendesk 3)
closes #1689
=> Fix title selector for ZenDesk 

src/scripts/content/kanbanist.js
toggl-button for Kanbanist was already merged in #1318, but it is currently broken, as Kanbanist has recently performed a major update including some changes to its styles. (https://github.com/mwakerman/kanbanist/pull/73)
This PR fixes it, and gets it working back again.
I tested this in Chrome and Firefox, and confirmed it works correctly in both.
=> Update kanbanist integration

src/scripts/origins.js
As title
Visit to-do.live.com:
Closes #1701
=> chore(origins): Add support for to-do.live.com

src/scripts/content/asana.js
Fixes #1730. Project titles may now have a non-breaking space in them, which we must replace.
* Under the test account, starting an entry should match the project
* (On master, it doesn't do this)
Fixes #1730.
=> fix(asana): Fix Asana not matching project names

src/scripts/content/evernote.js, src/styles/style.css
Fixes the Evernote integration
* Fix the selector for inserting the button and ensure it doesn't duplicate
* Change how the description is found. See comments - this will break if the class name is regenerated. We'll need to collaborate I expect. Only other option I saw was to hook into the Redux store but that's neither sensible nor responsible.
* Removes olden dead integration code/css
Fixes #1725
=> fix(evernote): Fix Evernote integration

.github/PULL_REQUEST_TEMPLATE.md
=> Fix English in pull request template

src/scripts/content/eventum.js
Similar integration as to GitLab: https://github.com/toggl/toggl-button/pull/1639
This is probably not useful on its own, but pre-requisite for https://github.com/toggl/toggl-button/pull/1683
=> Eventum: Add support for fetching custom fields as tags

src/scripts/content/zendesk.js, src/styles/style.css
- a1f2a05 - **feat(integration): Add Zendesk Agent Workspace support**
1. Enable Zendesk Agent Workspace (already enabled in test account)
Related #1696
=> feat(integration): Add Zendesk Agent Workspace support

src/scripts/content/slack.js, src/styles/style.css
A few selectors needed updating. Fixes #1729.
Channel heading button functions correctly
Message hover button functions correctly
Fixes #1729.
=> Update Slack web integration

src/html/popup.html, src/html/settings.html, src/scripts/background.js, src/scripts/common.js, src/scripts/components/BillableIcon.tsx, src/scripts/components/ContinueIcon.tsx, src/scripts/components/Summary.tsx, src/scripts/components/TagsIcon.tsx, src/scripts/components/TimeEntriesList.tsx, src/scripts/components/Timer.tsx, src/scripts/icons/play-green.svg, src/scripts/icons/play.svg, src/scripts/lib/db.js, src/scripts/popup.js, src/scripts/settings-theme.js, src/scripts/settings.js, src/styles/autocomplete.css, src/styles/edit-form.css, src/styles/popup.css, src/styles/settings.css, src/styles/style.css, webpack.config.js
- Add a dark mode toggle on the settings page
- When enabled, make the settings page, browser popup and integration popups dark
- Update the timer block slightly
- Turn it on and click around, is there anything that looks weird?
Closes #1575
=> feat(dark-mode): Add dark mode

src/scripts/content/zendesk.js, src/styles/style.css
Fix code to get the TE description based on the current ticket title. Also, a small improvement on the customer navigation button.
- Get a Zendesk account
- Open the ticket view
- Check if when starting the timer te description is the same as the ticket title
close #1794
=> fix(zendesk): Fix missing TE description

src/scripts/origins.js, src/scripts/settings.js
Fix integrations settings not showing the correct state for some domains
- Go to settings
- Integrations
- Check if when "Enable All" is clicked all the options are selected
- Check if when "Disable All" is clicked all the options are disabled
#1775
=> fix(settings): Integrations settings not "checking"

src/scripts/content/targetprocess.js, src/styles/style.css
Fix missing button on the new detailed view
- Go to your https://targetprocess.com/  account
- Check the User Stories table, the button should be there
- Check the User Story view, the button should be there ✔️ 
- In the User Story view, you should also get the project field filled if the project exists on your Toggl Account
close #1721
=> fix(target-process): Fix missing button on User Story view

src/scripts/background.js
Fix popup not showing after you open the task detailed view
> Steps to reproduce
Steps to reproduce the behaviour:
>Go to Todoist
In the list view, click the button icon to start a timer
Stop the timer
Click the ℹ️ to open task view
Close task view
Click the Toggl Button again
Nothing appears
close #1547
=> fix(todoist): Not showing popup after opening task

src/chrome-manifest.json, src/firefox-manifest.json, src/scripts/@toggl/ui/components/index.tsx, src/scripts/background.js, src/scripts/components/LoginPage.tsx, src/scripts/components/QuickStartGuide.tsx, src/styles/colours.css, src/styles/settings.css
- Add some more color from new color scheme
- Checkout the login and settings pages
=> Improve login/setting pages theme

src/html/popup.html
Update popup link to the new Webapp URL
=> chore(rebrand): Update webapp URL

src/scripts/background.js, src/scripts/settings.js
Fixes custom URLs.
On master:
* install extension
* go to settings
* do not enable any integrations from list
* set custom URL to `facebook.com`, pick any integration you want
* go to facebook.com, see content script for chosen integration not loaded
* uninstall extension
* switch to this branch
* repeat setting custom URL
* go to facebook.com
* your script should now be loaded
=> fix(background): Fix adding custom integrations URLs

src/scripts/background.js
Check `user-agent` sent to API calls
=> fix(background): Fix setting user-agent for API calls

src/scripts/origins.js
Fixes the Meistertask integration.
Not really much to say. The issue wasn't in the integration code itself, but the code was never loaded at all, because no `file` was specified for the domain.
Closes #1865
=> fix(integrations): Fix meistertask integration

README.md, src/scripts/content/gitea.js, src/scripts/origins.js
Adds a new integration with Gitea. Gitea is a community managed lightweight code hosting solution written in Go. It is published under the MIT license. 
Go to https://gitea.com or https://try.gitea.io to see it in action.
=> feat(gitea): Implement Gitea integration

src/scripts/content/gitlab.js
Fixes https://github.com/toggl/toggl-button/issues/1877
=> Update label selector for GitLab 13.5

README.md, src/scripts/content/odoo.js, src/scripts/origins.js, src/styles/style.css
This adds the Toggl button on almost all pages of Odoo's backend (Projects, Tasks, Tickets, Leads, ...).
All changes are tested across Chrome and Firefox.
This can be tested on https://demo.odoo.com/
=> feat(odoo): Add Odoo integration

src/scripts/content/todoist.js
fixed get label name in all page and get project name in single project page
Fixes #1899
=> fix(todoist): get project name and label name

src/scripts/content/zendesk.js
Fixes Zendesk agent workspace TE description
Updates the element selector to match the input
* Go to Zendesk, make sure Agent Workspace is enabled (it is by default on new accounts)
* Go to views, your unsolved tickets, and click any one
* Try to click "start timer" and check if the TE description is no longer undefined
Closes #1880
=> Fix Zendesk agent workspace TE description

src/scripts/background.js
* Build button
* Log in
* Start time entry in webapp
* See if button fetches it
=> chore(background): Update websocket url

src/scripts/background.js, src/scripts/common.js, src/scripts/content/toggl.js, src/scripts/content/zendesk.js, src/scripts/popup.js, src/scripts/settings.js
Fixes stop timer not working on Zendesk.
At initial load, the input where we get the description from is not yet available, so we weren't matching "undefined" vs the time entry title. This waits for the input to be there to set the title and compare.
This PR also tries to get rid of "Promise rejection returned a non-error" errors by making sure everything returns an error.
* Have Zendesk
* Start time entry
* See it actually changing to stop timer. Refresh the page to double check
* [Intercom case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/106481309201551)
_Reported by @VeljkoTN. Also interested: @TheSoloJake_
=> Zendesk: Fix stop timer not working

src/scripts/background.js
Adds an MVP for blocking websites.
Open youtube.com
Should close the tab
toggl-labs
=> feat(blockSite): add MVP

src/html/website-blocking.html, src/styles/settings.css
Fixes textarea styles in settings page in Firefox
Fixes font family on block page
Test Settings -> Distraction blocker styles in Firefox
Test Blocking Page styles in Firefox
=> fix(siteBlock) Fix fonts and textarea in Firefox

src/scripts/content/intercom.js, src/scripts/origins.js, src/styles/style.css
Handles Intercom.com and 2021 UI
Check out various Intercom places:
* conversations list
* single conversation (let's find a link somewhere, or contact me)
https://toggl.slack.com/archives/C015ZEJ3YKF/p1624452699432200
=> fix(intercom): Handle Intercom in 2021

src/scripts/content/zendesk.js, src/styles/style.css
Adds support for new (I think) Zendesk UI.
Button should be inserted here:
Dunno, but it looks like it's the only place now. If I deleted too much, let me know :sweat_smile: 
Closes #1979
=> fix(zendesk): Add support for new Zendesk UI

src/scripts/content/zendesk.js, src/styles/style.css
It seems that in https://github.com/toggl/toggl-button/pull/1985 I was too optimistic to delete legacy bits of Zendesk integration. This PR restores them and keep the new one separate.
Walk over #1992 and try to follow the cases.
Closes #1992
=> fix(zendesk): Restore previous Zendesk integrations

README.md, src/scripts/content/bugsnag.js, src/scripts/origins.js, src/styles/style.css
Adds the timer to Bugsnag, in the header of error events. See screenshot.
=> feat: Add Bugsnag integration

src/scripts/content/zendesk.js
Handles ticket id in new Zendesk UI
* Go to Zendesk (new UI, so might just sign up with new trial)
* Verify if Ticket ID is present in description
Closes #1995
=> fix(zendesk): Include ticket id in description

src/content/force.js, src/origins.js
- f021184 - **fix(salesforce): Improve description field auto-complete**
- Check if description field autocompletes across several Salesforce pages.
Closes #2024
=> fix(salesforce): Improve description field auto-complete

README.md
- **chore(docs): Fix broken link in CONTRIBUTING section**
- Check the README 😄 
Closes #2030
=> chore(docs): Fix broken link in README

src/styles/style.css
Moves integration-specific styles to track-extension
Cats are gray and builds are green 🟢
Closes https://github.com/toggl/track-extension/issues/2035
=> feat(styles): Move the integration-specific styles to track-extension

src/origins.js
- 93a2c62 - **fix(origins): Fix bad origin in Xero's entry**
- Check if it's possible to run the extension with the fixed origins. 👌
=> fix(origins): Fix bad origin in Xero's entry

src/content/taiga.js, src/origins.js, src/styles/style.css
Fixes integrations for taiga.io
Sign in to taiga.io with your github account and try to click around.
You're going to need to create both Kanban and Scrum projects.
Here's [the video](https://cln.sh/GsG56H) where to find the Toggl Button in both of them.
Check [where the button should show up](https://github.com/toggl/toggl-button/wiki/Where-can-I-find-the-Button%3F#taiga).
Closes https://github.com/toggl/track-extension/issues/1929
=> fix(taiga): Fix taiga.io integration

src/content/shortcut.js
fixes the shortcut toggl button due to a change in their markup
=> shortcut: input is no longer a direct descendent

src/content/atlassian.js
Fixes Toggl button in Jira.
The selector got broken again.
Make sure that Toggl button shows up on Board and Issue views.
[Setup instructions](https://github.com/toggl/toggl_api/tree/master/internal/integrations/services/jira)
[Test Jira credentials](https://github.com/toggl/toggl_api/tree/master/internal/integrations/services/jira) 
[Where can I find the button](https://github.com/toggl/track-extension/wiki/Where-can-I-find-the-Button%3F#teamwork)
Closes https://github.com/toggl/track-extension/issues/2055
=> fix(Jira): Fix Jira integration

src/content/atlassian.js
- 0a6180f - **fix(jira): Fix issue key missing in description**
- Go to an issue in Jira
- Click the 'Start timer' button
- Check if the issue key is automatically picked up
Closes #2059
=> fix(jira): Fix issue key missing in description

src/content/todoist.js, src/origins.js
Updates the todoist extension to align with their ui changes
Just check that nothing breaks.
closes #2065
=> fix(todoist): fix selectors for todoist ui changes

src/content/outlook.js
- 8edc8f2 - **fix(outlook): Fix Outlook's description autofill**
- Check if the button shows up in Outlook
- Check if the description is automatically picked up.
Closes #2045
=> fix(outlook): Fix Outlook's description autofill

src/content/zendesk.js, src/styles/style.css
- 303858e - **fix(zendesk): Fix Zendesk integration**
Button is showing up again and description auto-complete is fixed.
- Check if button shows up on Zendesk again
- Check if the ticked ID and issue title is getting automatically picked up for the description field.
Closes #2044
=> fix(zendesk): Fix Zendesk integration

src/content/todoist.js
Fix toggl button not appearing in todoist task view
Check if toggl button shows in task view;
Closes #2088
=> fix(todoist): fix todoist toggl button

src/content/gqueues.js
Fix the GQueues integration
- Create an account on https://gqueues.com/
- Play around and check if the button shows up as expected
- Check if we're getting the Project name based on the queue name
close #1869
=> fix(gqueues): Fix GQueues integration

src/content/github.js, src/origins.js
Adds toggl button to issues in github project page
- Go to github project page
- Click in any issue, it'll open a side pane
- Toggl button should show up
Closes #2090
=> feat(github): Adds toggl-button to new project pane

src/content/gitlab.js
- use `window.location.pathname` to get issue and MR ids (fix)
- use DOM instead of jQuery to get titles (refactor)
- update MR selector to fix querying MR title (fix)
ref #2083
=> fix(gitlab.js): get issue and MR id from pathname

src/content/fastmail.js, src/origins.js
Adds support for the Toggle Track button when viewing an email on FastMail.com
=> Added fastmail.com mail support

src/content/crowdin.js, src/origins.js
Adds the timer to Crowdin, in the header of the translation editor where translators spend most of the time.
=> feat: Add Crowdin integration

.github/workflows/bump-version.yml, .github/workflows/create-release.yml
Adds gh actions to bump package.json version and release.
The release action also dispatch the private repo action to bump the button version and create a PR.
Closes #2104
=> chore(gh-actions): Adds version bump and release actions

src/content/wrike.js, src/origins.js, src/styles/style.css
Update wrike selectors
1. Log into Wrike using the togglbutton account
2. Go to the personal space
3. Click in some task
4. The button should appear and get the Description and project correctly
Closes #2107
=> fix(wrike): Fix wrike button

src/content/asana.js, src/styles/style.css
Fix asana's integration both for the Task side pane and the board view.
Check if the button is showing up and working properly for asana.
Closes #2114
=> fix(asana): Fix asana board view button

package.json, src/index.d.ts
Adds type definitions.
Test the private repo locally to check if the type definitions are working.
Closes toggl/track-extension-core#294
=> feat(types): Adds type definitions

src/content/airtable.js, src/styles/style.css
- 46333cd - **fix(airtable): Fix button not showing up**
- Check if the button shows up correctly now. 👌 
Closes #2123
=> fix(airtable): Fix button not showing up 

src/content/github.js
- a2f551b - **fix(github): Fix button not showing in GH projects**
- Check if the button shows up now in a Github Projects page.
Closes #2132
=> fix(github): Fix button not showing in GH projects

src/content/google-calendar.js
- 197087c - **fix(gcal): Fix button in Google Calendar**
- Check if button shows up correctly on Google Calendar
Closes #2148
=> fix(gcal): Fix button in Google Calendar

src/content/github.js
- [fix(github): Fix github description pickup](https://github.com/toggl/track-extension/commit/24e26c37d5163567883ddb91bc5fda8b776a9c95)
- Check if Github issues description autocomplete is working. 👌 
- Also check it in Github projects. 👌 
Closes #2146
=> Fix Github issue's title and number autocomplete

src/content/outlook.js
Remove safe navigator from outlook integration since it would throw an error
=> fix(outlook): Remove safe navigator

src/content/zendesk.js
- [fix(zendesk): Render button in the new UI](https://github.com/toggl/track-extension/commit/5ff4e56030f815cb50d4b9fc265083f701db5495)
- Get an account with the new UI (HTML structure) and check if the button is there
Closes #2183
=> fix(zendesk): Render button in the new UI

src/styles/style.css
- [fix(rememberthemilk): Fix button not showing up](https://github.com/toggl/track-extension/commit/26f1f478f2b482a4b099e5e79b8f81754c226a6a)
Check if the button is now showing up for remember the milk
Closes #2217
=> fix(rememberthemilk): Fix button not showing up

src/content/visualstudio.js
Adds button to azure new UI
- [Enable the new boards hubs](https://toggl.slack.com/archives/C043ZPZQ2JC/p1687521693064579?thread_ts=1686119106.244789&cid=C043ZPZQ2JC)
- the button should show up when opening a task
=> fix(azure): Fix button now showing up in the new UI

src/content/todoist.js
- [fix(todoist): Fix popup input fields not being clickable](https://github.com/toggl/track-extension/commit/0158bf9f101d64684e08820163a66116c51dd162)
- Check if it's now working as expected
Closes #2235
=> fix(todoist): Fix popup input fields not being clickable

src/content/atlassian.js
- [fix(jira): Fix button not showing up](https://github.com/toggl/track-extension/commit/42b792a8d96e5d467dda0eb06f8fcf285d41b9e2)
- Check if the button is now showing up again
Closes #2243
=> fix(jira): Fix button not showing up

src/content/asana.js
- [fix(asana): Fix project auto-picker](https://github.com/toggl/track-extension/commit/b4e327840218d83889142e31de022d72e6ead91d)
- Check if project picker is working correctly on Task pane and List view (Board view unfortunately is not supported)
Closes #2236
=> fix(asana): Fix project auto-picker

src/content/wrike.js, src/styles/style.css
- [fix(wrike): Fix integration on new UI](https://github.com/toggl/track-extension/commit/34ec577fcdf9c38b154f94cf6a95432377990cbb)
- Check if the button is now showing up and picking description and project
Closes #1922
=> fix(wrike): Fix integration on new UI

src/content/anydo.js
- [fix(any.do): Fix Any.do integration](https://github.com/toggl/track-extension/commit/950f38d1e6f86a212c6bea5b8f8c49c6bea0eecb)
- Check if it's working correctly 👌 
- ⚠️ The button will still not show up on team/shared boards. We are working on a fix for it. 👍 
Related #2255
=> fix(any.do): Fix Any.do integration

src/content/asana.js
Fix asana integration for button on the task pane
Go to any project click on a task 
The button should be visible on top right for both cases (running TE and no running TE)
Closes #2263
Fixes this case from Intercom
https://toggl.slack.com/archives/C069JHPJQU8/p1704441321946629
(not sure if its safe to attach screenshots directly 🤔 )
=> fix(asana): Change task title selector

.github/workflows/bump-version.yml, .github/workflows/create-release.yml, .github/workflows/origins.yml
Switches GH Actions workers to run on Ubicloud
=> run GH actions on ubicloud

src/content/todoist.js
Fix multiple buttons adding to Todoist task header: https://github.com/toggl/track-extension/issues/2266
Demo with the fix applied:
Only 1 button should be present for the currently opened task.
Closes #2266
=> fix(todoist): Fix multiple buttons adding to Todoist task header

src/content/freshservice.js, src/origins.js, src/styles/style.css
Adds an integration to work with Freshservice support tickets.
The existing Freshdesk integration used to work for Freshservice, but Freshservice updated it's platform at the beginning of the year so the Freshdesk integration stopped working for it.
=> Freshservice Integration

src/content/hubspot.js, src/origins.js, src/styles/style.css
Adds the timer integration to tickets details page in Hubspot (CRM).
All changes are tested across Chrome and Firefox.
=> feat(hubspot): Add Hubspot integration

src/origins.js
https://github.com/toggl/track-extension/pull/2270#issuecomment-1978031677
The url for youtrack is updated
=> fix(youtrack): Update youtrack url

src/content/figma.js, src/origins.js, src/styles/style.css
Add toggl button on top bar of figma / figjam
Install 
Enable figma 
test
https://toggl.slack.com/archives/C043ZPZQ2JC/p1709105896973089
=> feat(figma): Add Figma Integration

src/content/trello.js
Update selectors 
- open trello.com
- open a project
- check that the button appears in the action menu
- check that the button appears on each checklist item
- close the modal
- repeat the test
=> fix(trello.js): update card container selector

src/content/shortcut.js, src/origins.js
Fix shortcut.com selectors
- open shortcut.com
- open a card
- check that the button appears in the action menu
=> fix(shortcut): update selectors

src/content/clickup.js, src/origins.js
Fix switching between sub tasks in clickup
Open a task 
Add sub tasks
Switch to sub tasks and start timer
closes #2299
=> fix(clickup): Switch subtasks correctly

src/content/hubspot.js, src/content/slack.js, src/origins.js, src/styles/style.css
Fix toggl button disappeared on channel toolbar
=> fix(slack): Fix toggl button disappeared on channel toolbar

src/content/_custom_nf_gitlab.js, src/content/_custom_nf_jira.js, src/custom-scripts.js
=> feat(custom): Add Jira and Gitlab custom scripts

.gitignore, src/content/atlassian.js
http://atlassian.net/browse/XYZ-123
Fix project on single page task
create or login to jira 
open a task 
click on task link in breadcrumb 
it opens in full page 
start a te it should pick up correct project (NOTE: there should be a matching project)
https://toggl.slack.com/archives/C043ZPZQ2JC/p1716748997367399
=> fix(jira): Fix project on single page task

src/content/trello.js, src/styles/style.css
=> fix(trello-clickup): Fix trello clickup for button styles

package.json, prettier.config.js, src/content/asana.js, yarn.lock
This PR fixes the Asana integrations by changing the selector in the spreadsheet for Projects and Tags.
As an extra, i added the prettier configuration of Toggl, used to keep the files up with code style. 
Go commit by commit, the last one is the fix.
Ensure that starting a TE from the Button will automatically resolve the Project and the Tags (if present) and if the 'Enable Automatic Tagging' is turned on.
closes: https://github.com/toggl/track-extension/issues/2321
closes: https://github.com/toggl/track-extension/issues/2317
=> fix(asana): tags and projects spreadsheet selectors

src/content/wrike.js
This PR will fix the Wrike selector that broke the Button.
Ensure that the TE starts on Wrike.
closes: https://github.com/toggl/track-extension/issues/2324
=> fix(wrike): selector broken

src/content/hubspot.js
Display button on contacts, deals, tickets etc 
Test it in hubspot
=> feat(hubspot): Display button on all objects using generic selector

src/content/hubspot.js
=> feat(hubspot): Update name selector for contact type pages

src/content/asana.js, src/content/todoist.js, src/content/zendesk.js, src/styles/style.css
Fix for asana zendesk todoist
While testing for top 10 apps
Zendesk was rendering buttons on inactive tabs as well this should help with performance 
Asana & Todoist details view is rendered on top of list view thus requires the autoTrack flag 
=> fix(autotrack): Fix for asana zendesk todoist

src/content/zendesk.js
Fix broken integration
@askides i have invited you to the zendesk trial account
=> fix(zendesk): Fix broken integration

src/content/asana.js
This PR fixes the double buttons appearing on the asana app.
1. See the [slack thread](https://toggl.slack.com/archives/C043ZPZQ2JC/p1737622269120009).
2. Check the behavior from the video (easier to understand).
3. Try to replicate.
4. It should not happen.
See [slack thread](https://toggl.slack.com/archives/C043ZPZQ2JC/p1737622269120009) here.
=> fix(asana): no more double button
