toggl/track-extension

- src/manifest.json
- src/scripts/content/drupalorg.js
This adds the timer link into the node tabs on Drupal.org project issues. Useful when developers are paid bounties on contributed project code. Screenshot: http://imgur.com/SVwf1JM
> Add Drupal.org issue node support.

- src/manifest.json
In Teamweek users are now redirected to app.teamweek.com not to new.teamweek.com.
> fix toggl-button for new teamweek subdomain

- src/styles/style.css
The way the icon was displayed in Wunderlist was sharp. I've adapted it to have the look and feel similar to other icons that are attached to task items in Wunderlist. 
I think this works better because the Toggl button does not distract the user from their task, by blending into the interface style.
> Change the Wunderlist integration to be more subtle and out of the way

- src/manifest.json
There's a native way to support extensions' settings pages. This is
defined in the extension's manifest.json [1]. Currently the option is
disabled when right clicking on the Toggl button, which is a little
confusing:
This commit makes it so the context menu shows "Options":
> Add a `options_page` field to the manifest

- src/html/settings.html
- src/scripts/background.js
- src/scripts/settings.js
Changes:
- Renames $timer/$idle to $nanny
- Adds suport for stop date and cb in #stopTimeEntry
- Add Discard Time Notification
Shows a notification to the user when she's been idle for at least 5min while
she was tracking some activity using Toggl.
The notification reads something like:
`You've been idle for 14m 53s while tracking "working on the landing
page".`
And two options are given to the user:
- Discard idle time
- Discard idle time and stop tracking
This notification/feature can be disabled via the new checkbox in the
eettings page, that reads like:
> Add Discard Time Notification

- src/scripts/content/todoist.js
Default implementation picks up projects names only from Todoist
project view. This modification extracts names from "project labels"
in filters and labels views.
> Make Todoist content script detect project names from different views

- src/scripts/content/toggl.js
Toggl's WebApp could offer a better user experience if it knew whether
the Toggl Button is installed or not. e.g., it could stop upselling /
advertising the existance of the Toggl Button to those users who are
already using it. It also provides additional information to draw a
better conclusion out of A/B experiments.
Toggl's WebApp and website can now tell whether the Toggl Button is
installed or not via checking the existence of `document.TogglButton`.
> Let Toggl's WebApp know that Toggl Button is installed

- src/manifest.json
Toggl's matcher was causing its content script not to run when
navigating/entering the WebApp or website by a url different than
`toggl.com` or `toggl.com/app/timer`.
e.g., if entering the WebApp via `toggl.com/app/profile`, Toggl's content
script would fail to execute since the matcher wouldn't report a match.
This change also allows executing the content script under
`fubar.toggl.com`, which was required for testing purposes.
`toggl.space` will wait for later.
> Fix Toggl content script matcher

- src/scripts/common.js
This adds a title-tag to the link, which makes ist much easier to see, which project I have to create in order to make this timer directly be attached to the right project.
> Add Title to Link for better Project identification

- src/manifest.json
- src/scripts/content/liquidplanner.js
Hello,
This PR adds some basic support for the LiquidPlanner project management tool. LiquidPlanner has its own timer, but I've found that lacking in flexibility compared to Toggl, that's why I've tried to integrate the Toggl button. I prefer logging my time in Toggl and then entering the data manually in the timesheet of LiquidPlanner.
This integration adds the Toggl button to the right pane, which shows the details of the selected package / project / task / milestone in LP. The task description is filled automatically.
I hope you'll find it useful - please let me know if there's any modification you would like to see.
Zoltán
> Add LiquidPlanner support

- src/html/popup.html
- src/scripts/background.js
- src/scripts/popup.js
- src/styles/popup.css
As requested in issue #411 
At first everything looks the same
Then we start doing something:
After we stop, the "Resume last entry" button appears:
When clicked the timer starts counting again with the same description, project and tags.
> Added a resume last entry button as requested in #411

- src/scripts/background.js
I literally just started the pomodoro timer when the fetchUser method is over if there is currently a time tracking entry. To test it I set the pomodoro time to a minute and used the android app to start the timer.
> Added pomodoro working when starting from elsewhere, as requested in #477

- src/html/settings.html
- src/scripts/background.js
- src/scripts/db.js
- src/scripts/settings.js
- src/styles/settings.css
- Added settings option for checkbox to turn on/off the feature
- Added settings option to set the time the workday ends
- Tried to fix issue with settings screen, it overflows when options are expanded
- Added notification when timer stops
- Added button in notification to continue the recently stopped entry
The notification
Checkbox and input field
> Timer can now be stopped at workday end, as requested in #245 

- src/scripts/content/redmine.js
If an issue has h2 elements, toggl button appears multiple times.
For example:
http://demo.redmine.org/issues/130734
I referred to #501 and applied same solution.
The solution also worked.
Would you please check my pr?
Thank you.
> Avoid multiple start timer links in Redmine

- src/html/settings.html
- src/scripts/background.js
- src/scripts/common.js
- src/scripts/db.js
- src/scripts/popup.js
- src/scripts/settings.js
As requested in #480 
- Setting shows dropdown with caption in the same format as in desktop app, <project name> . <client name>
- Default project is selected in popup
- Default project is selected in popup for integrations
> Default project setting added

- src/styles/style.css
Hopefully a fix for #621 . I'm not sure if there is a preference for `!important` declaration spacing in the CSS, but it's easier to change something that is consistent.
Line 35 starts the actual addition; others are just spacing.
Regex used to find `([^\s]+)!important` and replace `$1 !important`
> Fix for Issue #621 and consistent spaces

- src/scripts/content/youtrack.js
Users can have permission to change the project field and in this case the project name is in an a tag. 
This PR fixes that case and it was working before 6c6b3fa3f857fecadac2f2e4e02dba90d1bdd9ab.
> [YouTrack] Fix project name fetch regression

- src/scripts/content/gitlab.js
Hi there,
I've added the toggl button to the gitlab merge request page. When spending time on a merge request (e.g. reviewing it) I find it useful to have the toggl button available.
> Adding toggl button to gitlab merge request page

- src/scripts/content/github.js
Project name detection is working only for public Github projects, and not for private ones.
> Detect name for private Github projects

- src/html/popup.html
- src/scripts/autocomplete.js
- src/scripts/background.js
- src/scripts/common.js
- src/scripts/popup.js
- src/styles/popup.css
- src/styles/style.css
This PR adds Billable and tags icon to popup running timer. Hovering tag icons shows tags in tooltip.
__popup timer with icons__
Billable editing is shown if:
- selected project is in pro workspace
- No project is selected and default project is from pro workspace
Actions:
- Selecting project should set billable enabled if project has billable enabled.
- If billable is enabled and selected project is not billable the billable flag should not be updated.
- If project is in free workspace set billable false and hide billable row.
__Integration page__
__Popup__
> Add billable editing and billable/tags icons to timer

- README.md
Update some information on the README is outdated, such as Firefox support and Chrome-only features.
> Update Readme with Firefox information and Chrome exclusive features

- README.md
- src/scripts/content/feedly.js
- src/scripts/origins.json
This PR adds support for Feedly.
The timer locates right below the title in the metadata section of each story:
> Add Feedly support

- README.md
With version 1.1.0, custom domains are now supported in Firefox as well, thus this part of the README can be removed.
> Remove note on Firefox Permissions Restriction

- src/scripts/common.js
- src/scripts/content/github.js
- src/scripts/content/trello.js
- src/styles/style.css
Also modifies `togglbutton.render` to accept `mutationSelector` instead of `mutationClass` and trello content script since that was the only one that used `mutationClass`.
*Note: github's sidebar doesn't seem to slide down with the page anymore like it used to so having the button on the sidebar is not that much of a benefit anymore but meh...*
closes #669
> Button in sidebar for github

- src/scripts/common.js
- src/scripts/content/github.js
- src/scripts/content/trello.js
The new `mutationClass` thingy broke Trello buttons in some cases, because there was not one reliable selector to respond to in MutationObserver (different things happen when opening a card via a link, etc).
Tweaked the observer matching to match against ALL mutations, rather than just the first mutation in the array of mutations. Then specified multiple selectors for Trello checklists.
also some lint fix
Closes #738.
> Fix missing / temperamental Trello buttons

- src/html/settings.html
Fix a remaining "Chrome" in the settings (visible inside Firefox :p )
> Fix remaining 'Chrome' in settings

- src/scripts/content/rememberthemilk.js
Resolves issue #770
The button is now right to the task title as it worked before.
> Fixed "Start timer" not showing on Remember The Milk

- src/scripts/autocomplete.js
- src/scripts/content/asana.js
~~Button is back to the board view, but the board task detail view is hijacking the 'focus' event in some way that prevents our listener to be triggered. This solution leaves the user with a dropdown that at least opens on click, but not by tabbing to the input itself. ¯\_(ツ)_/¯~~
~~ps: I'm open to suggestions towards a solution that goes around whatever this view is doing with the focus event, but I couldn't find one myself. Curious thing is that you can open the console, create an event `new Event('focus')`, remove all the methods `stopImmediatePropagation`, `stopPropagation`, `cancelBubble`, `preventDefault`, then dispatch it and it will work. Buuuut if I do that inside the click listener (`autocomplete.js L33`) it doesn't work.~~
closes #759
> Fix button in the Asana board view

- src/scripts/db.js
In the case of subdomains and the like, we do some logic to try and
match a content script even if an immediate match isn't available.
The code was changed recently and the test ended up testing strictly vs null
whereas undefined is really what we're after here.
!x seems to be the case that stops jslint from shouting, whereas it
shouts at 'x == null' and '!(x != null)' and the like with current
settings.
Closes issue #781
> Fix origin checking (app.asana.com)

- src/scripts/content/github.js
GitHub is now mutating the whole html, apparently. So we can no
longer check for single elements changing.
Closes #787
> Fix github button disappearing

- src/scripts/autocomplete.js
- src/styles/autocomplete.css
This fixes the `max-height` calculation, taking into account scroll position.
Also prevents scrolling to top when focusing inputs; and `preventDefault`s the clear button, to also prevent scrolling to top.
Partially fixes #767
> Fix popdown height calc

- src/scripts/background.js
- ensures we interact with `https?` tabs only; closes #804
- fixes token removal; auth headers set only for API requests; closes #806
> Button patches

- src/scripts/background.js
- src/scripts/content/todoist.js
Todoist displays entries of a subproject below the main project's entries. Currently toggl-button just uses the main project's name as the Toggl project. This commit adds the ability to use the subproject name.
Any depth of project nesting is handled. We determine the name of the project, its parent, grandparent, and so on up the project hierarchy. Then we pass an array of these project names to the createTimerLink function so that each may be tried successively until one of them matches a Toggl project. (The matching doesn't happen until we click the Start Timer and it sends a message to the extension's background code, which I've enhanced slightly to accept a list of project names to look for.)
We determine the parent of a Todoist project by inspecting the indentation of their entries …
> Todoist: Use name of containing subproject as Toggl project

- src/scripts/content/toodledo.js
- src/styles/style.css
This updates Toodledo integration to the new layout
* Currently works on both old and new
* Adjusted button vertical alignment on both
* I couldn't find "goal" text to match up against projects. Removed it.
* Folder name currently maps to just a suffix to the task description (as it used to), but since we don't have something to try and match with the project name, we could use the **folder** name for project names on Toggl, instead of being part of the description.
* ^ left as this to match current/previous behavior
Closes #786
> Adjust to new Toodledo layout

- src/scripts/autocomplete.js
If body height is 0 (everything is absolute) it
messes up the height calculation for the popdowns.
This handles that case. But if eventually if we have a too low popup window on a body height 0 page, it could get cut off.
Closes #821
> Handle body height 0

- src/scripts/content/feedly.js
All buttons were added to the first card in Full view mode. This scopes
the selector to the current card. It fixes things for me.
closes #790
> Break up Feedly rave

- src/scripts/content/backlog.js
Possibility that 'titleElem.textContent' will fail to fetch.
Because, 'h3#summary' has meny 'span'.
> Fix. Backlog

- src/html/settings.html
- src/scripts/background.js
- src/scripts/common.js
- src/scripts/db.js
- src/scripts/ga.js
- src/scripts/settings.js
This adds a new option to the settings page:
Remember last project per service/url
Try the option out. It should:
* Remember the last project used for said service (eg. github) or url
* If it's the same as default project from settings, use that one
* When changing the option, should wipe the mapping
Closes #210
> Remember last project per service/url

- README.md
- src/scripts/content/dokuwiki.js
- src/scripts/origins.json
Creates toggl button anywhere on the site. 
Button is placed right bellow the header node and can be used for any activity on dokuwiki (reading, editing, comparing...)
> Add Dokuwiki integration

- README.md
- src/scripts/content/osticket.js
- src/scripts/origins.json
Toggl button for osTicket system. Can be used for tickets and tasks, layouts for both options is the same. Button is placed in the header of the ticket/task so it always visible.
__________________________________________________________________________________________
Timer description is in format: `<ticket/task number> [<ticket/task name>]`
> Integration for osTicket

- src/manifest.json
- src/scripts/background.js
As discussed in #430
@IndrekV in the end `ctrl+shift+s` didn't work so I choose `ctrl+shift+e` (`cmd+shift+e` on mac) users can rebind the command by accessing chrome://extensions/configureCommands
> Added keyboard command to stop/start timer

- src/scripts/background.js
- src/scripts/popup.js
- src/styles/popup.css
- src/styles/style.css
The thing I've missed the most. Being able to edit the duration to reflect the correct time I started working. Actually I just miss working on Toggl Button.
This PR adds duration edit field into the Extension icon popup Edit view.
Tested both in Chrome and FF and it seemed to be ok.
**Chrome**
**Firefox**
Some comments about the code.
- The duration field updates every second until user focuses the field. `PopUp.durationChanged` flag is used to determine if field should be updated or not.
- Firefox needed to validate the input in the time field as it allows to type in non numeric characters. That's why `isNumeric` function was added to PopUp.
- `(arr[2] || 0)` is used because in cases like `03:00:00` the value for some reason is `"03:00"` and this breaks the calculation as `arr[2]` is …
> Added duration field to extension popup edit view

- README.md
- src/scripts/content/spidergap.js
- src/scripts/origins.json
- src/styles/style.css
This PR adds Toggl button integration for [Spidergap360](https://www.spidergap.com), a popular 360-degree employee feedback tool.
- Matches the title of the page as description & Spidergap project name as Timer project
A screenshot of Design page - 
On Settings page - 
Passed `make lint` & submitted in one commit as suggested.
You can sign up [here](https://www.spidergap.com/signup) for Spidergap account.
> Add Spidergap360 integration

- src/scripts/content/gitlab.js
Hi!
I fixed https://github.com/toggl/toggl-button/issues/866 in this PR.
It can show button both (old or new) navigation now.
New navigation
Old navigation
Thank you.
> Fix gitlab issue page button

- src/scripts/db.js
This prevents errors when `TogglButton.$user` is not initialized.
> Handle missing TogglButton.$user

- README.md
- src/scripts/content/pagerduty.js
- src/scripts/origins.json
- src/styles/style.css
This adds a Toggl button inside the Incidents in [PagerDuty](https://www.pagerduty.com/).
The button is added to the right side column with the rest of the actions available for an incident. I attach a screenshot showing the placement of the button.
> added PagerDuty integration

- README.md
- src/scripts/content/clickup.js
- src/scripts/origins.json
It wasn't made totally clear to me if you need to see a live version of the Toggl button in our app, if it is then just let me know and I can get you credentials to a staging site right away.
We are implementing Toggl in our task view.  The two screenshots show Toggl started and Toggl stopped.  Please let me know if you need anything else from me.  Would like to get this integration going ASAP.  Customers have been asking for it!
> add integration for ClickUp

- src/html/settings.html
- src/scripts/background.js
Anchor tag buttons with hash based hrefs weren't all being prevented, causing url changes, and the href values weren't being used for the script, so I changed them to `javascript:void(0)`.
Noticied by @sjsnider in #904
> Fix anchor button hrefs

- src/scripts/content/gitlab.js
When you have a project that is nested under a sub-group, the way that the project is selected via the breadcrumbs breaks.
In this PR, we select the correct item in the breadcrumb list by selecting from the end, rather than the start of the breadcrumb list. That way, we always select the project as it's always the third last item when looking at an issue. (Project -> "Issues" or "Merge Request" -> Issue or Merge Request #).
> Fix for nested projects (GitLab 10.x)

- README.md
- src/scripts/content/airtable.js
- src/scripts/origins.json
- src/styles/style.css
This PR adds support for airtable.com. As it is almost impossible to guess tags or projects from an airtable dataset the integration only uses the datasets identifier as the description.
> Adds Airtable support

- README.md
- src/scripts/content/onshape.js
- src/scripts/origins.json
- src/styles/style.css
Added [Onshape Full-Cloud CAD](https://www.onshape.com/) to the toggl button.
- Matches _Onshape Document Name_ to _Toggl Project Name_
- Adds title of _Onshape Current Branch_ to _Toggl Timer Description_
- Adds the '3D CAD' tag to _Toggl Timer Description_
I ran `make lint` which passed, and tested it on the site in developer mode. Done in 1 commit per your request.
Thank you for making this cool tool :clap:
> added Onshape

- src/scripts/content/google-calendar.js
- src/styles/style.css
This PR adds support for the new Google Calendar Modern UI and resolves #919.
The Toggl Button is placed in the popup after clicking on an event, next to the delete, menu and close buttons.
> Added support for the new Google Calendar Modern UI

- README.md
- src/scripts/content/sentry.js
- src/scripts/origins.json
- src/styles/style.css
This PR adds Toggl button integration for [Sentry](https://sentry.io/).
- Matches the error type & detail as description
> Add integration for Sentry.io

- src/scripts/content/basecamp.js
- src/styles/style.css
Updates the selectors to fix start timer location on the todo page.
Closes #940 
Start timer link appears when hovering the todo list item.
This is what you should see:
> Fixed 'Start timer' link for Basecamp 3 todo view, closes #940

- src/scripts/content/habitica.js
- src/styles/style.css
* Updates CSS selector for zeh magical ⏺ for `habitica.com`.
#898 
The alignment with the other icons bothers me a bit, but its still functional. Would like help on that, if knows a fix.
> Fix Habitica Integration

- src/html/popup.html
- src/scripts/background.js
- src/scripts/lib.js
- src/scripts/popup.js
- src/styles/popup.css
This is something that I have been using for months now. It adds today's total and weeks total duration right under the timer in the Toggl Button popup. It might just be a good addition to the extension. Any feedback is welcome.
> Add day/week total duration text to popup

- src/scripts/background.js
- src/scripts/popup.js
- src/styles/popup.css
Prevents incorrectly displaying duration on 12h locale.
Also uses `pattern` to validate input.
Can't test it because no MacOS, but I'd be impressed if it still displays "AM" with `type="text"`.
Anyway, please test... And validate the validator regex :)
Closes #879
> Change duration input type to text

- src/styles/settings.css
Adjust settings dialog to prevent overflow, specially on screens with display scaling
Apparently Chrome is misbehaving when display scaling is turned on. We define our settings dialog's width and height, and Chrome makes the dialog window bigger. Sadly, the content does not scale up.
I tried some CSS to make Chrome respect the dimensions, but couldn't. At least there's no more overflow.
* Have high resolution screen, change display scaling
* If you also have this feature on your OS (Mac, Linux), please let me know how that looks for you
* See issue, before and after.
* Check specially if there are no uneeded scroll bars, and if the scroll bars are not clipped.
Kinda closes #845
> Adjust settings dialog to prevent overflow

- src/scripts/content/atlassian.js
So, this should handle the new Jira design.
this should close #905
> Fix toggl button inside the new Jira modal

- src/scripts/content/asana.js
- src/styles/style.css
Put the button back on the Asana board view, when the user hovers a task. See #979
Like this:
> Fix Asana board view

- src/scripts/background.js
This should fix #984
The header should now show the correct time for Today based on the users local timezone.
> Fix Header Showing Incorrect Time Tracked Today

- src/scripts/background.js
This now selects the most recent Sunday, Monday, Tuesday, ect. instead
of the one in the current week starting on Sunday. This caused errors
and should fix #989
> Fix Header Showing Incorrect Weekly Time Tracked

- src/scripts/background.js
The extention should now update the icon when the currently running
timer is deleted. It will also set that deleted entry that was running
in the latest stopped entry for the resume shortcut.
This should fix #993
> Fix Sync Issue with Entry being Deleted

- src/scripts/content/atlassian.js
Accounts for additional H1 elements that might be present in the card description. Previously, adding `# Some title` in the description would break the card.
Fixes #992.
> Fix displaying timer on Jira board cards

- README.md
While developing an integration I noticed Firefox automatically loads `manifest.json`, regardless of the selection of `manifest_ff.json`. This might help some people in the future.
> Adds Firefox install from source instructions

- README.md
- src/scripts/content/heflo.js
- src/scripts/origins.json
- src/styles/style.css
This PR adds Toggl button integration for HEFLO.
- Matches the workitem subject and current task label as description
- Matches process name and version as description on process designer
- Matches the user current application name as project
> Add HEFLO integration

- src/manifest.json
- src/scripts/background.js
Add a message listener to respond with extension version as a safe-guard, to the previous `window.TogglButton` beacon.
> Add install beacon to notify extension installed

- src/scripts/popup.js
Make 'Recent entries' non clickable
**Note:** Use of arrow function as discussed with @langri-sha we are now using ES features supported by Firefox ESR
> Fix error popup on clicking "Recent entries"

- README.md
The old git clone url wasn't working for me. This fixes that.
> Update git clone command in Readme

- README.md
- src/scripts/content/bugherd.js
- src/scripts/origins.json
Adds a bugherd.com integration with loading the project name and the task number as description as "Task XXX".
> Adds Bugherd Integration

- src/scripts/background.js
The pomodoro notification should remain visible on screen until user activates or dismisses the notification.
It fixes issue #937.
> The pomodoro notification should remain visible on screen

- src/scripts/content/visualstudio.js
I've updated some of the selectors for the new VSTS markup to fix #1019 
The only thing I'm not sure of is what element was initially used for the project value.
In this PR, it's the value in the project selector, which is CRM in the screenshot.
Here you can see that the button is on the page again:
> Fixes Visual Studio Integration

- src/scripts/content/teamwork.js
The extension wasn´t working anymore because of HTML changes we made in Teamwork Projects, this PR is changing the currently used selectors.
> Teamwork Projects UI FIX

- src/scripts/content/asana.js
Closes #1068
* The button should appear in board-card detail view
* The button should appear in the standard task detail view
(Right before the close/'X' button)
* Fixed integration
* Made the button appear before the close button
> Fix asana board task view

- src/scripts/content/atlassian.js
Related issue: #1053
Desk case: case/725339
#1053 seems to be a common issue between trello and jira users and is probably related to the backend of the extension db/background scripts.
This PR doesn't address that issue specifically but is a fix for the most common error on [bugsnag](https://app.bugsnag.com/toggl-dot-com/toggl-button/errors/5b2ac4200ecf63001722ae2a?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[search][0][type]=eq&filters[search][0][value]=atlassian)
> Fix Jira integration parentElement null error

- src/scripts/content/slack.js
- src/styles/style.css
This update fixes the issue with the first letter being removed from a private channel. However, it also changes the current behaviour of the Toggl button in Slack. I think it's an improvement, but that may just be my opinion. Changes included here are:
- Project is now taken from the channel name ***not team name as before***
- Hyphens (`-`) and underscores (`_`) are converted to spaces
- Project name is converted to Title Case
- Task description is left undefined for the channel title button
- Adds a Toggl button to the hover message actions list
- Task description for this button is taken from the message body
- Fixes #1002 
- Fixes #601
> Updates Slack integration

- src/scripts/background.js
* Assign a `default_wid` to `TogglButton.$user`
* Prevent type error at https://github.com/toggl/toggl-button/blob/39e7cd52b1a3676dcb0b8a95e35cbbf963472d6a/src/scripts/autocomplete.js#L452
See `/keybase/team/toggl.frontend/toggl-button/1053/info.md` on keybase for instructions.
```shell
open /keybase/team/toggl.frontend/toggl-button/1053/info.md
```
on windows open `k:\team\toggl.frontend\toggl-button\1053\info.md`
For some users particularly ones who created account via an invite thus
are part of a workspace that they don't own the api wasn't returning the
`default_wid` field in the response in the `v8/me` endpoint. 
Related #671 
Closes #1053
> Handles v8 API response with not default wid

- src/scripts/content/atlassian.js
Atlassian released a new interface that replaces the side panel when viewing issues inside a Kanban board.
I'm not sure what `projectName` is supposed to contain (currently empty on an issue page on the board I tested on), but I used the dropdown from the side with a fallback to the first item of the breadcrumb.
> New Atlasian Cloud Popup in a Kanban board

- src/styles/style.css
Using `float: right` was causing Toggl button to drop to lower line, cropping it.
Added specific rule for card in agile board, so it does not float.
Please make sure this doesn't break elsewhere in Youtrack.
> Add custom style for YouTrack agile view

- src/scripts/content/phabricator.js
- src/styles/style.css
The toggl button wasn't appearing in the workboard view because the css selectors have been updated. Details here: https://github.com/phacility/phabricator/commit/e077d2f#diff-8aa808d5f88c9da253dbd34ad07755dbL343.
This PR:
- Updates css selectors for Phabricator.
- Changes the location of the toggl button in tasks and revisions. Now it is placed in the actions list.
---
- `make lint` finishes successfully.
---
- Phabricator:
- Phacility:
> Update Phabricator integration

- src/html/settings.html
- src/styles/settings.css
* Increase height for nag reminder view in first tab
* Increase height for pomodoro option in second tab
* Tweak test sound button styling and position in second tab
* Before
* After
* Before
* After
* Open extension settings
* In the **"General"** tab click on **"Remind me to track"**
* The **"Minutes since stopping last Time Entry"** option should be visible
* In the **"Pomodoro Timer"** tab click on **"Enable Pomodoro Timer"**
* The **"Test"** button should be visible and not clipped
Closes #1074
> Fix clipped options in extension settings

- src/scripts/content/atlassian.js
- src/styles/style.css
Add support for recent Jira update.
- Login to Jira account, go to kanban and open some task
- Button should be available on the right:
close #1081
> Add new Jira dialog support

- src/scripts/content/meistertask.js
Add support for Meistertask 2.0.
Quick note: new layout has very, very strange selectors. Well, all they use only few classes for everything (like `.kr-text`, `.kr-view`, and so). That's why selectors look so bad 🤕 
If someone has better solution, feel free to review this.
close #1106, close #1102, close #1093
> Add support for Meistertask 2.0

- src/scripts/content/sentry.js
The button stopped working for sentry.io. The project name class is no longer in the DOM. I've fixed this by changing it to the value of the project select class element.
> Fixed sentry.io button

- src/scripts/content/atlassian.js
The current implementation of the selectors for the new Jira sprint popup was broken because the classes keep changing randomly (on every release is my guess).
My previous implementation stopped working after a few days, but this one should be more stable as it relies on more "functional" attributes.
> Update Jira selection so it does not use classes

- src/styles/settings.css
Ensures the settings dialog is overlaid above the content. Please see issue on how to reproduce.
Fixes #1153.
> Fix settings dialog pushing content

- src/html/settings.html
- src/scripts/lib/bugsnag.js
- src/scripts/lib/db.js
- src/scripts/lib/ga.js
- src/scripts/settings.js
Please review after #1145.
Adds a new settings tab for controlling the submission of usage statistics and error reports.
Please make sure to:
- ensure the by default we're sending data
- toggling the control as disabled sticks (open/close settings page)
- updating the controls at runtime instantly enables/disables the submission of data
> Add telemetry controls

- src/scripts/background.js
- src/scripts/lib/db.js
Fix multiple issues arising from notifications triggering their action when closed, rather than only when the user interacts with the notification. The main offender was the timer starting automatically whenever the notification is shown.
See commit for details. Fixes #778, #1116, #1170.
I mainly tested the "reminder to track time". I set this to 1 minute, and started+stopped the timer to trigger the reminder behind the scenes.
When the notification shows, if you either don't do anything or choose "close" (not on macOS+Firefox), the timer **should not start**. 
It's the same for all notifications, though. Needs testing on both Chrome and Firefox, and we should test Windows Firefox.
> Fix notification actions triggering without user input

- src/scripts/content/youtrack.js
- src/styles/style.css
YouTrack has recently introduced new layout for single issues. Since YouTrack 2018.3 the ability to choose between "old" and "new" layout for single issues was removed, now only the "new" layout is available.
This pull request adds support for this new layout. 
The toggl button is located on the right:
> Add support for new YouTrack layout

- src/scripts/content/atlassian.js
- src/styles/style.css
Fixes the Jira integration on the new issue page, and shares a small improvement for project name to the older page as well. You can test this by clicking a link on an individual issue in the "Toggl Button Project", so that a new tab opens with the issue filling the whole page.
Fix Jira integration on the "list of issues" page(s). You can test this by going to the "All issues" page. The selected issue will have a button inside of it in the right pane.
Fix Jira "sprint modal" integration not picking up the project name. You can test this on the "Toggl Button Scrum Project" project, viewing the current sprint, and clicking ona ny issue.
Remove some old dead versions of the sprint modal integration.
There was a contributor PR open for this in September (#1121, I'll update the user later), …
> Fix Jira integration on new SPA layouts

- src/firefox-manifest.json
- src/html/settings.html
- src/scripts/settings.js
- src/styles/settings.css
Previously permissions were broken and/or disabled since the start due to slight differences in the extension API, which seem to be cleared up now.
unfortunately the diff is quite bad. Closes #1060, closes #1169  and probably others that I'll find.
- Show the permissions tab in Firefox again
- Change firefox manifest to no longer have wildcard permission by default
- Change firefox manifest to have a wildcard permission in *optional_permissions*, in the same vein as Chrome. This allows us to request permission on any origin at runtime (i.e. turn on/off domains and add custom domains).
- Remove redundant conditional Firefox code in the settings module, consolidating Chrome/Firefox code as they function exactly the same now.
Other:
- Extract each permissions event handlers to its own named …
> Re-enable permissions in Firefox

- src/scripts/content/backlog.js
Fix a selector, and removed some element type specificity from other selectors to reduce risk.
I removed the `if !descriptionElem return` as we want errors to be captured in bugsnag.
Fixes #1181.
When testing, you may have to add a custom domain in the extension settings for `myaccount.backlog.com`.
> Fix backlog integration

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/integration-changes-and-updates.md
- .github/ISSUE_TEMPLATE/integration-request.md
Add our first multiple issue templates.
I have tried to use a format and language that is easy to follow, and not assuming much technical knowledge or software lingo. New integrations and existing integrations are split to help prioritising and getting the right info for each issue. 
* Integration request - for asking us to add a brand new integration.
* Integration changes and updates - to ask for an integration to support a new feature, or to improve existing functionality
* Feature request - for asking us to add a new feature to the extension.
* Bug - for reporting any bug. I did not find value in splitting up integration bugs and general bugs, I wrote two different ones then thought they're just gonna be used for the wrong things, in addition to the 2 different integration templates.
> Add multiple issue templates

- src/scripts/background.js
- src/scripts/common.js
- src/scripts/lib/bugsnag.js
* Send the release version again *(At some point the environment variable must have changed, but the client was left in the dust)*
* Catch rendering errors from async rendering (`MutationObserver`). If this is a valid change, we'll probably see significantly more useful errors coming in.
I forced tested this by breaking the wunderlist extension locally, and saw that my error only showed up after the change to error catching was made (if you want to do this yourself, you have to open background page debugging).
* Send integration name to bugsnag. The "name" of content script errors will now be like: `Content Error [wunderlist]`. Looks like someone intended to do this originally, but never actually sent their `errorSource` variable.
> Fix various bugsnag issues

- src/scripts/content/slack.js
- src/styles/style.css
Fixes #1220.
To test:
1. Use slack web client
2. In any channel, hover over a message.
3. You should see a toggl button in the hover-toolbar (this was entirely broken prior)
4. This button works and does not have style issues in the popup
> Fix slack integration in individual messages

- src/html/settings.html
- src/scripts/background.js
- src/scripts/lib/db.js
- src/scripts/settings.js
This setting controls whether service integrations will automatically add any tags/labels detected to the time entry (and therefore creating them in Toggl, too). It defaults to **disabled**.
The main reasoning stems from feedback in #1217, where users have their own tags in the integration - unrelated to the way the team tracks time -  and now the Toggl workspace is being polluted with dozens of new tags since automatic tagging was added to that integration.
This affects behaviour of **very few** other existing integrations (`<= 4` at best), so any unrest when this setting is released should be minimal.
Closes #1217.
> Add setting to control automatic tagging

- src/scripts/content/todoist.js
Some useful project logic was mistakenly removed in #1197 . This re-introduces it. 
The logic being re-introduced looks for the closest project in the Todoist project hierarchy that matches something in the user's Toggl workspace. This was existing behaviour that shouldn't be removed.
Resolves #1223, partially reverts #1197. 
Second commit refactors the module according to eslint/prettier, and tweaks the integration to provide functions to the timer link instead of raw values (so that it can retrieve values at runtime after any changes, not only on load).
* Lowest level project in Todoist project hierarchy, which matches an existing project in your Toggl workspace, is added to the time entry.
* Tags are added to the timer if the Todoist task has any tags or not.
* If you open a task and …
> Restore Todoist nested project logic

- src/scripts/content/freshdesk.js
- src/styles/style.css
Fixes #1228 
The button was placed in an element that was not necessarily removed when navigating between views. 
Move the button to a deeper element that is removed/cleaned up when navigating. The element in question is the "left side" of the toolbar, which updates pretty much all the time and is a much more "correct" solution.
This PR also contains a free improvement to fetch the description every time button is clicked (fixes issue when using task navigation on the right side of the page).
> Fix Freshdesk Mint button duplicating

- src/scripts/content/google-calendar.js
- src/styles/style.css
Update calendar selectors; hopefully more safe now.
Remove dead code for old version(s) of calendar. I don't think any of that was still functional anywhere.
Button appears and works when you click on an event and see the "popup".
FYI the behaviour can be *slightly* funky - when you submit the toggl edit form, the calendar popup will close. Probably not trivial to work around, not working on that here.
Closes #1234.
> Fix Google Calendar new UI

- src/scripts/content/asana.js
Auto filling description when new asana task create and immediately start.
Asana task name change and TogglButton click immediately.
I can see filled changed task name in description area.
issue #1212
> Fix asana task button

- src/styles/style.css
The `#notion-app a` selector Notion uses is more specific than `.toggl-button.notion` and thus the `cursor: pointer` declaration is not overriding the `cursor: inherit` that Notion sets.
This commit adds the `#notion-app` ancestor selector with a descendant combinator before the selector for the Toggl Button, increasing the specificity to 3, above Notion's specificity of 2.
Ref (Original PR): #1203
> Fix styles not being applied

- src/styles/style.css
Fix google calendar event button with graphics.
without graphics
with graphics
Chrome and Firefox work well.
Fix #1242
> Fix google calendar with graphics

- src/scripts/background.js
- src/scripts/common.js
Fixed button text when multiple use.
The cause of this is here.
https://github.com/toggl/toggl-button/blob/fe156e95a020d33b49843109804bb39c5d472add/src/scripts/common.js#L460-L464
This lines added for multiple buttons in page.
But it deactivate not only page button but also in form button.
https://github.com/toggl/toggl-button/commit/fe156e95a020d33b49843109804bb39c5d472add#diff-06c72a7198e9adae75546aab4cd17b53
Tested across Chrome and Firefox.
Fix #1247
> Fix form button text for multiple use

- src/styles/style.css
This avoids integration buttons interfering with user copy/paste behaviour. Don't want to move any buttons around. Resolves #1249.
I couldn't forsee this causing any problems so I applied it as default style. Can just apply it to Jira for now if there is any reason to.
See it resolves the described issue
resolves #1249
> Avoid highlighting of timer link text

- src/scripts/content/ticktick.js
- src/scripts/content/wunderlist.js
fix filling description text when task rename (Wunderlist or Ticktick.com)
Tested across Chrome and Firefox.
fix #1065
> fix wunderlist and ticktick task rename

- src/scripts/background.js
Ensures tags are included when continuing a time entry from the toolbar popup.
This was a regression introduced by the "enable auto tagging" flag. Resolves #1259.
`createTimeEntry` is used by all methods of creating or updating an entry; and it's not always clear where the request comes from. In the relevant cases, I have ensured that the request `type` is following through and check against that to determine if tags are included.
The only time tags should **not** be included is an event unrelated to continuing entries:
* starting a new timer from a tag-supported integration (E.g Todoist) when the `Enable autotagging` setting is disabled.
We are fixing:
* …
> Fix continued entries not copying tags

- src/scripts/content/google-calendar.js
- src/scripts/content/slack.js
- Google Calendar: ignore "create event" dialog
- Slack: ignore non-text message types
All still works good.
> Handle some error cases in noisy extensions

- src/scripts/lib/autocomplete.js
The root cause is we cannot refer tag input value within event `keyup` listener  `TagAutoComplete`, also there's no preventDefault when enter key is pressed.
I need to refactor `TagAutoComplete.prototype.addEvents`, To make it possible to make things works as expected.
Fix #1216 issue.
> Fix tag input behaviour when using keyboard

- src/scripts/content/salesforce.js
- src/styles/style.css
Related #734. We've been advised that the Console view is probably quite important, so I have added basic support for it.
Also Remove redundant Salesforce integration code, Remove lightning suffixes from Salesforce class names
In regular "Sales" mode, check the following (may need to select a record from the list)
* Task https://um5.lightning.force.com/lightning/o/Task/home
* Contact https://um5.lightning.force.com/lightning/r/Contact/0034J0000022CbpQAE/view
* Account https://um5.lightning.force.com/lightning/r/Account/0014J000002YJ2OQAW/view
(there are many others, but I'd say focus on what appears to be …
> Add basic support for Salesforce Lightning's Console views

- src/scripts/content/trello.js
Resolves #1280.
* Now using correct class name to find the board name directly; old one changed and broke.
* Lint
* Button in cards side-menu should work fine again and include the project name (if board name matches - use `Toggl Button Project` as board name in test account)
* Buttons in task lists inside cards also work fine.
Resolves #1280.
> Fix Trello project name selecting

- src/scripts/content/freshdesk.js
Fixes Freshdesk Mint after UI update. Closes #1099 (again).
The old FreshDesk integration in the same file has also been linted/reformatted.
Should work for all tickets, and still pick up tags (tags have moved to a properties sidebar).
Closes #1099 (again). Closes #1304.
> Fix Freshdesk Mint 2019-02 UI

- src/scripts/common.js
*Merging to feature branch*.
Cleans up link activation/deactivation further.
The `togglbutton.links` list was in fact a "memory leak" of detached DOM elements and would infinitely increase in size over time. I did not see it used anywhere else.
It also caused buggy functionality with "activating" the active timer link on the page, due to old link references never being removed.
Also a bonus fix for stopped links appearing green when they should not. 
Second commit fixes "infinite re-render". Upon activation, the button class list would be mutated too much and cause re-renders to happen in integrations that did not have mutation selectors. In future, we should …
> Refactor "link activation" to query DOM instead of storing list of links

- src/scripts/content/todoist.js
- src/styles/style.css
* Uses minimal button for Todoist integration.
* Improves hover behavior in Todoist integration by using the proper parent hover div (`task_item` instead of `task_content_item`).  `task_content_item` is lower in the DOM, so hovering parts of the task would not cause the toggl button to appear.
Tested in chrome
Split off from [here](https://github.com/toggl/toggl-button/pull/1277#issuecomment-462009197)
> Use minimal button for Todoist integration

- src/scripts/lib/bugsnag.js
Fixes some filename replacements for source mapping on bugsnag. The chrome prefix was missing from the regex.
The `.*` added to the beginning is to account for some strange strings that sometimes come in, like `@ [12]/<@moz-extension://......`
Looks good
> Fix stack filename replacement for Chrome

- src/chrome-manifest.json
- src/firefox-manifest.json
- src/html/settings.html
- src/scripts/background.js
- src/scripts/lib/bugsnag.js
- src/scripts/lib/db.js
- src/scripts/settings.js
- src/styles/settings.css
*Depends on PR #1296, base is set to that branch at the moment.*
*Note*: This PR basically solves the core of "Settings standalone page" as well - #1287. I needed to move it in order to use `confirm()` etc. Other issue is probably still valid but estimate may be reduced for the final cleanup.
Adds a button in a new area at the bottom of the settings page. 
Clicking it will:
* Show a confirmation with option to cancel
* Re-set all `storage.sync` settings to default values
* Log out the user. This is the safest way to "reset" the extension and its state.
Settings don't break, extension doesn't get into a …
> Add feature to reset all settings

- .eslintrc.js
- package-lock.json
- package.json
- src/chrome-manifest.json
- src/firefox-manifest.json
- src/html/settings.html
- src/scripts/background.js
- src/scripts/common.js
- src/scripts/content/toggl.js
- src/scripts/lib/bugsnag.js
- src/scripts/lib/db.js
- src/scripts/lib/ga.js
- src/scripts/popup.js
- src/scripts/settings.js
- src/styles/settings.css
* Use `webextension-polyfill` for all extension API usages
* Remove extra `onMessage` listener in `db.js` (which was part of the background page), because it broke everything in the new API. It's moved to background script. We cannot have multiple listeners acknowledging messages.
* Use `storage.sync` instead of `localStorage` for all settings. Things like cached `projects list` and `clients list` are still in local storage.
* Some misc bugfixes / improvements along the way.
**Also merged from #1329 already:**
* Basic standalone settings page was required
* Adds a button in a new area at the bottom of the settings page to reset all settings.
Ready for poking to …
> Use webextension storage

- src/scripts/background.js
- Fix end of workday check
- Enable Stop at end of work day in button settings
- Start a TE
- Wait for ~30 seconds
- TE shouldn't stop automatically
Closes #1341
> Fix Timer stops abruptly if stop at end of day is enabled

- package-lock.json
- release.config.js
- src/scripts/settings.js
- Refactor and reuse `nag-nanny-to`'s event listener for both fields.
- Track `package-lock.json` from CI.
- Open toggl-button's settings
- Edit the from-to settings under "Remind me to track"
- Reload settings page
- Changes should persist
> Note: @tcrammond I'm thinking of changing the event-listener to respond to `change` instead of `blur`, do you foresee any problems?
Closes #1339
> Fix input changes not being saved

- package-lock.json
- package.json
- src/scripts/lib/bugsnag.js
- webpack.config.js
- Upgrades bugsnag lib to latest version (v6)
- Run npm audit to fix security vulnerabilities 
- On HEAD commit run
```shell
BUTTON_BUGSNAG_API_KEY=0e9beda13e7926e30c1e0fc2e170a82a yarn release
```
- Load the built extension
- Open network tab in devtools for the background page
- Enable the github integration
- Open https://github.com/toggl/toggl-button/issues/1350
- Inspect payload on bugsnag's request the stacktrace should be the modified one
> **Note:** Removing last commit before merging.
Closes #1350
> Upgrade bugsnag to v6

- src/scripts/lib/db.js
Removes some redundant "settings migration logic" and fixes bug where `false` settings would get overwritten with default values any time the extension was loaded (i.e. on browser start). *(This migration condition is redundant because we have a new migration [here](https://github.com/toggl/toggl-button/blob/master/src/scripts/background.js#L2155))*.
Closes #1353.
Before this change, you would observe the following with local extension running:
1. Change some settings, e.g. set `Show post popup` to `false`.
2. Reload via `about:debugging` / `chrome:extensions`
3. You will see in the background script …
> Fix some settings being overwritten with default values on load

- src/scripts/background.js
Resolve https://app.bugsnag.com/toggl-dot-com/toggl-button/errors/5c90c3e73728f4001bb193b7?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[release.seen_in][0][type]=eq&filters[release.seen_in][0][value]=latest&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[event.class][0][type]=ne&filters[event.class][0][value]=Content
Add a defensive check. This seems to have come about because of async functions and the various ways this can be triggered. Not looking to refactor the flow at this time.
Should look like this error can not happen anymore even if it wanted to.
> fix: Fix errors on workdayEnd when $curEntry is null

- src/scripts/lib/bugsnag.js
- src/scripts/lib/db.js
- src/scripts/settings.js
Ensure default settings are loaded in case of invalid value. Horrible bugs aside, this is valuable so that user can recover seamlessly if anything does go wrong with the stored settings.
`async`-ness of `load()` is removed because it was not used correctly (😬) and can definitely cause severe settings problems in some browsers, it seems.
First time I loaded Toggl Button into Firefox **Developer** Edition, all of my settings became `null` 😱 . The root cause is probably the incorrect `async` usage - each value was not retrieved before it was attempted to be saved again in `load`, so it was saved as `null`. *(This re-saving is on the cards to remove, but this fix is …
> Ensure default settings are loaded in case of invalid value

- src/html/settings.html
- src/scripts/settings.js
- src/styles/settings.css
- New layout for settings page(s)
- Permissions may be searched by integration name
- Permissions shows both integration name and the domain
- Center settings container to not look awkward on wider viewports
- Super-secret dark mode settings
- Delete the "remember active tab" feature. Its statefulness has broken the settings more than once. It can come back when settings is stable if desired.
- Open and test all settings across both browsers
- To test dark mode paste this incantation in the settings view console
```javascript
document.documentElement.classList.toggle('dark')
```
Closes #1313
> Revamp Settings UI

- README.md
- src/scripts/content/kanbanist.js
- src/scripts/origins.js
Add Kanbanist integration.  
Kanbanist is an inofficial tool that adds Kanban-like task management for Todoist. The toggl buttons will appear in each Kanban box just beside the task title when you hover the cursor on Kanban boxes. 
- https://kanban.ist
- https://github.com/mwakerman/kanbanist/issues/33
On hover:
On hover:
> Add Kanbanist integration

- README.md
- src/scripts/content/scrapbox.js
- src/scripts/origins.js
- src/styles/style.css
This PR adds [Scrapbox](https://scrapbox.io) integration.
[Scrapbox](https://scrapbox.io) is a new kind of wiki application.
This PR adds Toggl Button to elements which shows line metadata.
> Add Scrapbox integration

- src/scripts/background.js
- Fix start/stop TE automatically options
- Extract the latest entry from the time-entries list instead of `localStorage`
- TODO for a different issue remove calls to `localStorage` from files other than `db.js`
- Enable start/stop automatically option
- Restart the browser
- The latest TE should continue
- Close the browser
- The running TE should stop (takes a few seconds to reflect on the other clients)
Closes #1375
> Fix automatic start/stop feature on browser open/close

- src/scripts/components/TimeEntriesList.tsx
- src/scripts/components/Timer.tsx
- src/scripts/popup.js
- src/styles/popup.css
* Shows the running entry's project and tags in the toolbar popup. Description will get ellipsified `...` if it's long. Description is allowed to take up more space, but project will still have some spacing around it.
* Any part of the running timer can be clicked to edit the entry now.
* Shows the running entry's project and tags in the toolbar popup.
* Description is correctly ellipsified
* Nothing weird happens with elements flowing etc.
* Any part of the running timer can be clicked to edit the entry now.
* The stop button still stops the entry correctly.
* No issues clicking a particular part of the …
> Show running entry project and tags

- src/scripts/content/wordpress.js
- src/styles/style.css
Button wasn't appearing on WP 4.8.3, 4.9.8 and 5.1.1
Fixes Wordpress integration for
* I tried on a Wordpress 5.1.1 that had two types of post forms. The new, 5.x.x, and the previous one. Can verify both codes from a single WP installation. I also tested on an actual 4.9.8 installation.
Fixes #1362
> Fix wordpress integration

- .github/CONTRIBUTING.md
- src/scripts/content/microsoft-to-do.js
- src/scripts/origins.js
- src/styles/style.css
- Restore toggl button support for Microsoft To-Do
- They seem to have changed their domain from todo.microsoft.com to to-do.microsoft.com
- Also insert the button to the left of the star button
- Enable Microsoft To-Do integration
- Go to to-do.microsoft.com 
- Add some tasks
- Toggl Button should appear in the task rows
Closes #1312
> **Note:** After merging the PR update the screenshot at https://github.com/toggl/toggl-button/wiki/Where-can-I-find-the-Button%3F#microsoft-to-do use the one on this PR
> fix(microsoft-todo): Add support for to-do.microsoft.com domain

- src/scripts/lib/utils.ts
- Add a catch block around `URL` constructor call
- Return false if the url is not parseable by `URL`
Closes #1393
> Fix Toggl URL check

- src/scripts/background.js
- src/scripts/content/nozbe.js
- src/styles/popup.css
- src/styles/style.css
- Fix Nozbe sidebar style-leak
- Scope `hidden` class to `toggl-button-` to prevent style leak
- Add new integration to task list
- Enable nozbe integration
- The  sidebar should look fine with the integration enabled
Closes #1397
> Fix overriding of Nozbe Sidebar styles

- package-lock.json
- src/html/popup.html
- src/scripts/background.js
- src/scripts/common.js
- src/scripts/lib/autocomplete.js
- src/scripts/popup.js
- src/styles/edit-form.css
Fixes `TAB` behaviour in the "edit forms". It broke due to layout change in the popdowns. Should be fixed both in the toolbar popup when editing an entry, and when creating a new entry via timer button in an integration.
Removed some olden numbered tab indexes as part of it - let's avoid that now. I'm not sure it is necessary to do anything like that anymore.
Added some `tabindex` management for the `dialog fields` - set to `-1` when a popdown is focused so that focus is not trapped forever (without this, can't `SHIFT+TAB` backwards).
Closes #1402.
Test important integrations as well as in the popup.
> fix(popup): Fix tab shortcuts in the edit form

- src/scripts/content/wrike.js
Fixes #1388. Some errors on missing elements caused the whole thing to break. It now renders without erroring out. Wrike rendering is a bit awkward and the button looks a bit displaced on some views - not resolving that here, just fixing breakage.
Also integrates work from PR #1379, and doesn't include `taskId` when it couldn't be found.
> fix(wrike): Fix errors breaking the Wrike integration

- src/scripts/content/atlassian.js
- src/scripts/origins.js
Fixes #1408. Removes an integration block that's not needed.
To repro on master:
1. Ensure `atlassian.net` origin is enabled
2. Go to the [test Jira](https://togglbutton.atlassian.net/secure/RapidBoard.jspa?rapidView=1)
3. Click on a card after everything has loaded
4. See the Toggl button appear briefly and then vanish again
After changes, to ensure that the "sprint modals" still continue to function (I removed a whole block of code):
1. Go to [scrum project sprint view](https://togglbutton.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=TBSP)
2. Click on an item
3. The modal will appear and a Toggl button should be inserted. Once.
All changes …
> Fix Jira kanban board buttons

- src/scripts/lib/autocomplete.js
- I am not really sure why the problem occurred and why this solves it 🤷‍♂ 
- Open TE edit Popup
- Select a project from below the first fold (out of current scroll view)
- It should select correctly
Closes #1418
> Fix project selection

- src/scripts/components/TimeEntriesList.tsx
- Fix large project names overflowing container and hiding the resume TE button
- This PR adds some overflow styling to avoid that
- Add a really long project name to some TE
- Stop the TE
- The continue TE button should be visible
> Fix large project-names hiding continue button

- src/scripts/popup.js
Tweaks behaviour of the "ticking" duration input you get when editing the running TE.
The interval should no longer live on forever in the background, stacking up every time you use the form.
I checked on the pomodoro interval, and that one seemed sane.
If you want to see the old behaviour, add some logging to the interval in `showCurrentDuration` on master.
> Fix duration input interval behaviour

- src/html/settings.html
- src/scripts/background.js
- src/scripts/index.d.ts
- src/scripts/lib/db.js
- src/scripts/lib/utils.ts
- src/scripts/settings.js
- src/styles/settings.css
- Add a review prompt on the settings page
- Show review prompt on opening settings for _active users_
- Open settings
- In the console paste 
```javascript
localStorage.setItem('dismissedReviewPrompt', false);
localStorage.setItem('timeEntriesTracked', 30);
location.reload();
```
- It show show the review prompt
- Click the review button to land on the correct store for your browser
- Click on the close on the bottom right of the prompt to dismiss it
Closes #1295
> Add passive review prompt

- src/chrome-manifest.json
- src/firefox-manifest.json
- webpack.config.js
- Turns off `node.global` shim
- Removes the  `'unsafe-eval'` permission from Chrome and Firefox manifests
- Test everything the button can do
- Login/Logout
- Start/Stop/Edit a TE
- Add project/tags
- Test at least 1 integration
- Poke some settings
- Hope for the best 🤞 
Closes #1427
> Stop webpack from using eval

- src/scripts/content/trello.js
- Fix trello card integration not working in cases where the Move button is absent
- Public boards
- Single board workspaces
- Enable Trello integration
- Access a [public board](https://trello.com/b/qdXnbUBi/ultimate-job-search-kanban-template) 
- Access a [single board workspace](https://trello.com/c/0XSyRtJB/1-oompa-loompa)
- The Trello card integration should work in both cases
Closes #1423
> Fix Trello integration when the 'Move' button is missing

- src/scripts/content/atlassian.js
Includes the Jira issue's title in the timer description once again.
I think the DOM changed, as well as a small oversight in the code, so we were no longer getting the issue title.
The issue title shows in your timer description, along with the issue number.
> fix(jira): Fix timer descriptions in Jira

- src/scripts/lib/ga.js
Fix client ID not being sent to GA
Looks sane and that the client id will be included in request now.
> Fix client ID not being sent to GA

- src/scripts/settings.js
Fix the "Disable all" button in the integrations settings page. 
The problem was that `customOrigins` actually had all the origins, so everything was getting skipped. Then I noticed the values of the **real** custom origins are strings whereas the rest are objects, hence why I'm using `typeof origin === string`. 
First of all, before installing the extension:
1. Add `console.log('origins ::', origins);` to line 559 of `settings.js`
2. Run `yarn webpack-cli --mode development`
3. Load the extension.
Then:
1. Enable some (or all) integrations
2. Add a Custom Integration
3. Click "Disable all" 
4. Check if all checked integrations are now unchecked
5. Check the console to see the disabled integrations, the custom one shouldn't be there. …
> fix(settings): Fix "disable add integrations" button

- src/scripts/content/atlassian.js
✔️ Split the issue page and board page renderers into two separate ones.
✔️ Patch another error I found in Bugsnag related to the 2017 page
1. Enable the integration (custom Atlassian togglbutton.atlassian.net)
2. Check [board page](https://togglbutton.atlassian.net/projects/TB/issues/TB-2?filter=allissues&orderby=priority%20DESC) and [issue page](https://togglbutton.atlassian.net/browse/TB-16) to make sure the button is showing up correctly
3. Make sure the project and description selectors are working
4. Check there are no renderer errors in the console
Closes #1346
> Fix Jira's board page and issue page integration

- README.md
- src/scripts/content/corgee.js
- src/scripts/origins.js
- src/styles/style.css
Adds support for [Corgee](https://corgee.com) to Toggl Button
Adds minimal type Toggl button icons to two places in Corgee
Global tasks view with cards:
(Global tasks view with cards can be opened by selecting "Tasks" item in the left sidebar)
Project view with tasks:
(Project specific tasks view can be opened by selecting one of the projects under the "Project Folders" section in the left sidebar)
Closes #1432
> feat: Added support for Corgee

- src/html/popup.html
- src/scripts/background.js
- src/scripts/common.js
- src/scripts/lib/autocomplete.js
- src/scripts/popup.js
- src/styles/edit-form.css
- src/styles/popup.css
- Prefix edit-form css rules with `TB__`
- Fixes style-leak on webapp
- Mostly affects Firefox, because the button styles are injected after the main css
- Load the dev button 
- Open a reports page on webapp with some data on it
- The download button should look sane
Closes #1446
> Fix style leak prefix edit-form css with TB__

- src/scripts/content/rallydev.js
show toggl button in task details view (rallydev integration)
nope
#1445 
1. go to [rallydev](https://rally1.rallydev.com/slm/login.op) website
2. go to team status
3. click on user story/task
4. toggl button should be visible in right pane details view
5. click user story/task number from right pane
6. toggl button should be visible next to task number in user story/task full view
> Fix Rally integration - show button in task/us details

- src/scripts/content/asana.js
Removes dead /old integration code.
Fixes project auto-selection in Asana (when the Asana project exactly matches an existing project inside Toggl workspace).
The element selection became stale after changing task. It now selects the project element fresh when we need to retrieve the project name.
Repro in issue doesn't happen anymore. No matter how many tasks you switch between Asana, the project will be picked up correctly. (In our Asana test account, tasks in `Toggl Button` and `Toggl Button Project` should match a project in toggl).
Closes #1457.
> fix(asana): Fix project selection in Asana integration

- src/scripts/content/openproject.js
- src/styles/style.css
- Remove all buttons from the Work Package list, for example here: https://community.openproject.com/projects/openproject/work_packages
- Add work package ID to description. The new description format is `[OP#<Work Package ID>] <Work Package Subject>`. This helps to find the the work packages at a later point of time, as the work package subjects might change but the IDs do not.
- You can check that nothing has changed layout wise for the view when a work package is open, for example here:
https://community.openproject.com/projects/openproject/work_packages/1899/activity
Closes #1471
> OpenProject: Remove toggl button from work package list.

- webpack.config.js
Fixes webpack loosing assets between rebuilds.
* `npm start`
* `dist/chrome`, `dist/firefox` should have `manifest.json` and `images` directory full
* modify some content script
* files should still be there 
Closes #1468
> Fix local dev server losing the manifest after changes

- src/scripts/content/visualstudio.js
Container DOM nodes in query view are cached so it's needed to get an active (visible) container to prevent rendering all buttons in the first container.
Should be tested with different task views (I only tested normal and queries views)
closes #1459
> fix(visualstudio): use correct container to render button

- src/chrome-manifest.json
Adds `minimum_chrome_version` to the chrome manifest file. 
It seems this is all you need to do, even though I couldn't confirm. I tried previewing a draft release, but the webstore doesn't display the minimum required version in their UI. 
Does anyone with experience maybe know if this is it? 🤷‍♀ 
closes #1391
> chore(chrome): Increase minimum required version for Chrome

- src/scripts/popup.js
Removes the bug where the cursor would jump after focusing duration field in popup edit view. This PR adds focus event detection that will stop the timer from updating duration field data
1. Start timer
2. Go to edit view
3. Click on duration field (somewhere other than the end) 
4. See that the cursor is not moved to the end
If the duration field loses focus and was not edited the timer should continue tracking. If the user edited the field timer will not continue tracking and pressing Done will update the duration.
closes #1417
> fix(popup): Fix cursor jump when focusing duration

- src/scripts/popup.js
- fd069fa - **fix(popup): Fix tag/project dropdown toggle**
There are two event handlers configured that are triggering the popdown (by calling the `toggleDropdown` function):
1. A focus event configured in the class `TB_Dialog_field` (parent of the element with id `toggl-button-(tag|project)-placeholder`)
2. A click event configured in the element with id `toggl-button-(tag|project)-placeholder`
This commit removes the 'focus' event handler from `TB_Dialog_field`, since it seems that it's no longer necessary.
Another possible solution would be to add a `e.stopPropagation` on the click event handler.
- Check if the tag/project dropdown stays open after clicking on it (more info on #1422)
Related #1422
> fix(popup): Fix tag/project dropdown toggle

- src/scripts/content/google-mail.js
Enables support for popup email view that [drag-app](https://dragapp.com) uses.
> feat: Enable gmail integration to work with Drag-app popup view

- src/scripts/content/youtrack.js
When starting a timer from card popup in agile board wrong issue ID was
referenced. I believe that the logic for finding the element containing
the issue ID was querying the whole document resulting in the wrong ID
in most of the cases. This should fix that by finding the Toggle
button's parent element and then finding the child element of that
parent that contains the issue ID.
1. Go to YouTrack agile board with multiple cards in multiple lanes
2. Open issue view by double clicking on a card
3. Start a timer
4. Issue ID in the description should now correctly reflect issue ID of the card
closes #1509
> fix: YouTrack integration

- src/scripts/content/basecamp.js
- src/styles/style.css
List of improvements:
- Prevents overlap with default Basecamp hover actions
- Uses minimal button style for list
- Makes button always visible in the card view
- Makes button visible after the task is completed (so the user doesn't forget to stop the timer) in both list/card views
List view:
Card view:
Please test:
⚠️ This is for Basecamp 3, not 2! If using the Toggl Button test account you'll have the option to choose:
#1426
> fix(basecamp3): Improve layout and UX

- src/scripts/content/todoist.js
- Fix selector for fetching labels (tags) from new Todoist interface
- Enable automatic tagging
- Go to todoist
- Start TE for a task that has some tags
- Created TE should also have the same tags
Closes #1529
> Fix Todoist tags integration

- src/scripts/background.js
- src/scripts/index.d.ts
- Fix tags with same names across workspaces being overridden/hidden in popdown
- Create same tags across different workspaces
- The duplicated tag should still show up in the autocomplete list
- Verify that removing `TogglButton.$user.tagMap` hasn't caused any regressions
- See #1535 for detailed info and case
Closes #1535
> Fix Tags being overridden

- src/scripts/background.js
Add a defensive check when generating tags elements. The root cause data fetching is not something I want to touch in a quick fix.
Nothing errors, try empty accounts too.
https://app.bugsnag.com/toggl-dot-com/toggl-button/errors/5db83c7dc2408c0019d02792?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[error.status][0]=new&filters[release.seen_in][0][type]=eq&filters[release.seen_in][0][value]=latest
> Fix possible error with tags rendering in edit forms

- src/styles/autocomplete.css
- src/styles/edit-form.css
Follow up to #1532.
There were more elements not visible or just weird because of Todoist's dark mode. These fixes should improve things in other tools using dark mode as well.
Make sure Todoist works in both "Todoist" (default) and "Dark" themes. I also tested with Github but It'd be nice to check in a third tool just in case.
List of things fixed by this PR (all in Dark theme):
1. Label for the stop timer button inside the edit form didn't appear:
2. Add new tag button looked weird:
3. No placeholder in popdown filter inputs:
> fix(Todoist): Fix time entry edit form on dark mode

- src/scripts/content/google-calendar.js
- Refactored Google Calendar implementation to support popup and detail view
- Added implementation notes in `google-calendar.js`
I verified the following in both Chrome and Firefox on macOS 10.14.6:
- The popup view works the same as before.  I did not change the underlying selectors for the popup view dialog.
- Detail view implementation works the same across both browsers
- Closes #955
> fix(google-calendar): Support Google Calendar detail view

- src/styles/style.css
Hides the Toggl Button in the list view when the Any.do delete button should be visible (i.e. when task is completed).
- if a task is active, the Toggl Button should be displayed
- if a task is complete, the Any.do delete button should be displayed
Closes #1525
> fix(any.do): Hide in list view when delete button is visible

- src/scripts/content/todoist.js
Adds the button to todoist's new task view.
Open a task in task view and test the button there (selected task and subtasks):
*Important note:* project selection is not great. See #1549 for details.
Another note: there is a bug with Todoist's dark mode, where the subtask's actions aren't visible on hover unless you disable this:
Closes #1528 
Opened https://github.com/toggl/toggl-button/issues/1547 for the below issue:
> WIP note: there is a bug in Firefox where if you track in the list view, then the task view (or vice versa), the button popup doesn't appear (does still track though):
> feat(todoist): Add to task view

- src/scripts/background.js
Syncing issues are cropping up between button and other clients. Websocket being closed and then not reconnecting is a likely cause.
Let's reimplement reconnection attempts.
Logic at time of opening PR:
- Each retry waits 5 seconds longer than the last.
- The maximum retry wait time is 1 minute
- The maximum number of retries is 30, at which point it gives up
Ideally we'd have some way to rekindle it in the UI, but it requires some further thought. I would like to merge this without adding on new features first.
I do think there really needs to be some way to easily kickstart it again after it goes  wrong.
To test the continual reconnection logic, I recommend:
- …
> Enable websocket reconnection attempts

- src/scripts/background.js
It is not an error, and this attempt to report is actually generating errors in itself 🤦‍♂ [Bugsnag](https://app.bugsnag.com/toggl-dot-com/toggl-button/errors/5dcc1428f0b376001b2edb48?filters[event.since][0]=30d&filters[error.status][0]=open)
The events do not contain anything useful according to wise folks on the internet (for browser security reasons). According to the spec it'll be a generic `1006` with little no information about what actually went wrong with the connection.
Looks sane
> chore(websocket): Do not try to report socket onerror events

- src/scripts/background.js
Checks if a socket is already open or connecting before trying to replace it.
Prior to this change, multiple sockets are being opened by the extension, because there is no check. A new socket is opened each time the toolbar popup is opened, for example.
At some point we need to refactor this more, for today we need to fix the problem.
- Socket is still opened
- You do not get multiple sockets opened at any point (check Network, WS in background page inspector)
- If you close the connection `TogglButton.websocket.socket.close()`, it does eventually get reopened.
- You still do not ever get multiple sockets opened.
Before: multiple connections can exist at any …
> fix(websocket): Ensure only one websocket connection is opened

- README.md
- src/scripts/common.js
- src/scripts/content/zammad.js
- src/scripts/origins.js
I request the merge of the zammad integration. Zammad is a helpdesk and support software see  https://zammad.com.
The toggl button is placed in the ticket details in the tool-area at the top right (see screenshot below).
The changes have been linted and the integration has been checked in Chrome and Firefox.
> feat: add zammad integration for toggl button

- src/scripts/common.js
Checks the page height every time the popup is opened. This fixes a bug where after the Chrome window is shrunk, the position is wrong.
Currently in master:
1. Open Trello in a fairly long (700px+) Chrome window
2. Resize the window so it's quite short
3. Open a card
4. Scroll down until you can just see the "Start a timer" link
5. Click the link
6. The popup is partially hidden
This should no longer happen.
Try out some more combinations of resizing and opening the popup in Trello and other integrations.
Hopefully fixes #1498
> fix(popup): Get page height when opening popup

- src/scripts/components/TimeEntriesList.tsx
Opens the edit view when clicking on an existing time entry.
WIP note: it currently opens the existing edit view, which only works when there is a currently running timer, and shows details of the currently running timer. #1565 will rework this view.
1. Click on an existing entry
2. The edit view should open
Closes #1564
> feat(edit): Open edit view when clicking on an existing time entry

- src/scripts/content/asana.js
Improve/fix project selection in list views.
It now tries to extract the project from the project cell (if spreadsheet view), falling back to the page header if it is a project page.
See that the project is or isn't selected correctly in all the different situations you can find. Recommended to use the test account and the `Toggl Button Project` project in Asana.
- Regular list views
- Task detail view
- Project page list views
- Task detail view
- Others?
> fix(asana): Fix project selection in list views

- src/html/settings.html
- src/scripts/@toggl/time-format-utils/format-duration.ts
- src/scripts/background.js
- src/scripts/components/Pomodoro.tsx
- src/scripts/components/Summary.tsx
- src/scripts/components/TimeEntriesList.tsx
- src/scripts/components/Timer.tsx
- src/scripts/lib/actions.ts
- src/scripts/lib/timerUtils.js
- src/scripts/popup.js
- src/scripts/settings.js
- src/scripts/shared/use-countdown.ts
- src/scripts/shared/use-duration.ts
- src/scripts/shared/use-interval.ts
Adds an optional focus mode while a pomodoro timer is running - shows a countdown timer instead of the usual entries list.
Current issues:
- The countdown doesn't update at the exact same time as the duration :(
- It works in the extension popup, but not when the popup is opened as a separate page
Turn the focus mode option on and start a timer.
Click on the countdown to stop it early.
Open the popup during a working 
Closes #1567
> feat(focus): Add focus mode for pomodoro

- src/scripts/popup.js
- src/scripts/shared/use-duration.ts
#1539  :star2: What does this PR do?
Fixes a bug where editing the running entry also stops it, if a completed entry has been opened previously. 
Steps to reproduce:
- Open edit view for any past entry
- `dataset.stopTime` is set to that entry's stop time
- Open edit view for the currently running entry
- `dataset.stopTime` is still set to the previous stop time
- Submitting the form stops the entry
This change clears `dataset.stopTime` when opening the currently running entry.
- Follow the instructions above to verify the bug in master
- Try the same again in this branch
> fix(popup): Stop time cleared when opening running entry

- src/scripts/lib/autocomplete.js
Fixes autocomplete popdown height to be based on `window.innerHeight` instead of `body` element
Check main integrations with different window sizes, all should render good.
Rebase it on top of https://github.com/toggl/toggl-button/pull/1604 and check if it works well for Worksection too 
Closes #1606
> Fix autocomplete height to be calculated based on window's innerHeight

- .github/CONTRIBUTING.md
- src/scripts/content/dom-integration.js
- src/scripts/content/generic-toggl.js
- src/scripts/origins.js
- Adds generic DOM integraiton option
- Updates contirbuting doc to add a note about new option
- Add demo website to showcase the integration
Built on top of #1599 from @mskrip 
- Enable `DOM Integration` for a page with the specified schema
- It should render a usable toggl button
Closes #1599 
Closes #1524
> Add DOM integration option

- src/scripts/content/notion.js
- src/scripts/origins.js
- src/styles/style.css
Fixes Notion integration for some (hopefully longer) time, until it changes DOM structure again 😅 
Toggl button should appear in dialog view as visible below:
Closes #1454
> Fix Notion integration

- src/scripts/content/workflowy.js
- src/styles/style.css
Workflowy styles had gone a bit out of date. This fixes them! Original workflowy integration PR: #1335
Copied from the original PR
1. Navigated to [workflowy.com](https://workflowy.com/).
2. Created a bullet.
3. Hovered over the bullet (the circle part).
4. Observed how the toggl button appeared. (pass)
1. Navigated to [workflowy.com](https://workflowy.com/).
2. Created a bullet.
3. Clicked on the bullet (the circle part). This makes it so that that bullet is now the top bullet.
4. Clicked the more options menu on the right.
5. Observed how the toggl button appeared. (pass).
Original integration PR: #1335
> fix: Workflowy styles

- src/scripts/components/Summary.tsx
Restores the "Today" total in the popup. Unlike the total given at the top right of each day block, this total includes the current running timer - note difference between the two numbers:
Check it's there and the number is correct
Closes #1619
> fix(popup): Restore current day total, inc running timer, to summary

- src/scripts/background.js
- src/scripts/components/LoginForm.tsx
- src/scripts/components/LoginPage.tsx
- src/scripts/index.d.ts
- src/scripts/lib/messaging.ts
- src/scripts/settings.js
- Adds fallback login option in case regular login fails
- Log out from button and webapp completely
- Fallback login will only show up in case regular login fails
- Use attached diff to force login view navigate to `chrome-extension://EXT_ID/html/login.html?source=quick-start`
- Try logging in using fallback form button should still work
```diff
diff --git a/src/scripts/components/LoginPage.tsx b/src/scripts/components/LoginPage.tsx
index 40858f0..bf8143e 100644
--- a/src/scripts/components/LoginPage.tsx
+++ b/src/scripts/components/LoginPage.tsx
@@ -52,7 +52,7 @@ async function login (setState: React.Dispatch<React.SetStateAction<LoginState>>
}
export default …
```
> Add Fallback login

- src/scripts/content/intercom.js
Adds a button to intercom's article edit page:
Go to intercom's articles section, open an article and look for the button.
Requested internally
> feat(intercom): Add button to KB article edit page

- src/scripts/settings.js
- Normalizes the input to lower-case before comparing it to lower-case integration names
- Try the integration filter with upper, lower, mixed case input
- It should filter correctly in all cases
Closes #1628
> Fix Integration filter not working with upper-case text

- README.md
- src/scripts/content/brokerengine.js
- src/scripts/origins.js
- src/styles/style.css
Adds the Toggl timer to the BrokerEngine task list and loan views. BrokerEngine is a mortgage broker software for growing firms (https://www.brokerengine.com.au/)
The changes have been linted and has been tested on both Chrome and Firefox.
None
> feat: Add BrokerEngine integration

- src/scripts/content/notion.js
- src/styles/style.css
adds timer link to notion main page (extends #1612)
- wasn't able to get the hover text to update when the page updates, but the timer will start with the correct description :(
also adds a wrapper to make the timer link look more like native page actions
try out the timer from the notion main page
check the new style looks ok
follow on from #1612 for #1454
> Add button to Notion main page

- src/scripts/content/asana.js
Re-adds the button that was changed in #1636, as the new Asana detail view isn't available to 100% of existing users right now. It should be live for everyone soon (https://github.com/toggl/toggl-button/pull/1636#issuecomment-572724899) but putting this PR here in case anyone has time to review and release beforehand, or the rollout gets delayed.
Unfortunately we don't have access to any accounts still on the old system, but this is just the [old code](https://github.com/toggl/toggl-button/blob/309f0e92d042a46f2d8183306a79e2ef6bebf02f/src/scripts/content/asana.js#L72) added back in and it worked fine before :see_no_evil: 
[Slack notice](https://toggl.slack.com/archives/C8H3UCQ9W/p1578547062009100)
> Restore Toggl Button for Asana's old task detail view

- src/scripts/content/atlassian.js
Attempts to dodge all other elements when picking the time entry description, by focusing on the issue link itself. This only contains the issue ID.
This seemed simplest and works in all pages at the moment.
Ensure that timer buttons work as expected with the correct descriptions in all of our test projects
- "Toggl button project"
- "Toggl button Scrum project"
- "Next generation scrum project" ( this is where the issue could be reproduced) 
Fixes #1644.
> fix(jira): Fix "copy link" text being included in time entry descriptions

- src/scripts/content/trello.js
Fixes Trello card closing when you click on the edit popup's project or tag dropdowns.
1. Open a Trello card
2. Click the "Start timer" link
3. On the edit popup, open the project or tag dropdown
The Trello card should no longer close in the background.
First two commits are from #1625 which should be merged first.
Closes #1622.
> Fix Trello card closing when opening project/tag dropdown

- src/scripts/content/asana.js
Change description to a selector function, to get the latest description when button is clicked
Note: button doesn't turn red on click, see issue #1650 
On master:
1. Go to Asana's My Tasks page
2. Add a new task
3. Type in a name
4. Click the Button
5. There is no description <- fixed on this branch
Closes #1646
> fix(asana): Get task description when button is clicked

- src/scripts/background.js
- src/styles/edit-form.css
- Make the "Done" button 100% wide
- Move the "Cancel" button next to the "Delete" button
This makes the popup's edit form look more like the integration popup (where "Done" is 100% wide) and groups the less commonly used "Cancel" and "Delete" options together.
Buttons should still work as before.
Closes #1632
> Rearrange edit form buttons

- src/scripts/common.js
The popup edit form is closed when there's a click outside it.
1. Start a timer in any integration
2. Click inside the popup (it should stay open)
3. Click outside the popup (it should close)
Closes #1585
> feat(edit-popup): Close popup edit form when user clicks outside

- src/scripts/common.js
- src/scripts/lib/autocomplete.js
Update the way the project and tag dropdowns' max height is calculated. It should stretch out and end just before the bottom of the page (assuming there are that many entries), e.g.:
Long list when near top of page:
Short list near bottom of page:
Open the dropdowns in a few integrations, and also the popup.
The dropdown should not stretch outside of the viewport.
Closes #1659
> fix(autocomplete): Fix autocomplete dropdowns being too long

- src/scripts/background.js
- src/scripts/lib/autocomplete.js
There's bug if tag containing `::` is added, autocomplete code gets fatal error because `::` indicates DOM selector, not verbatim text.
This was extracted out of https://github.com/toggl/toggl-button/pull/1639
Docs:
- https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector
> fix(autocomplete): Fix escaping of tag names in html title attribute

- src/scripts/content/workflowy.js
Fix workflowy following UI changes. The "more menu" markup changed a little bit and the nesting broke things. It is tricky as the DOM is updated whilst using these menus and it can overwrite the classes we depend on when checking if we should inject a button.. but it seems to work again for now.
* Using the 'more menu' next to individual task works fine
* Using the 'more menu' next to the title works fine
Closes #1662.
> Fix Workflowy integration

- src/styles/autocomplete.css
Stop long task names from wrapping and overlapping other content in the projects dropdown
Have some tasks with *very* long names, check that they don't overlap each other anymore in the projects dropdown.
Fixes #1667.
> fix(autocomplete): Fix long task names overlapping in project dropdown

- src/scripts/background.js
- src/scripts/lib/db.js
Remove some `checkPermissions` logic that would automatically open the login page if it thinks you don't have any permissions enabled, on load/login (with login meaning, any time user is fetched, I think).
Do not think this is needed any more with the new onboarding page(s).
Everything seems sound, and we're not missing out on anything as a result of this change.
Closes #1663.
> Remove "checkPermissions" logic on load/login

- src/scripts/content/trello.js
- src/styles/style.css
- Updates insertion selector
- Fixes positioning code
- Open a Trello card with a checklist
- Button should be visible on hovering over a checklist item
Closes #1672
> Restore support for Trello check-lists

- src/scripts/content/gitlab.js
If Gitlab merge request had a description, the button was shown two
times since the redender selector found two matching elements.
Fixes that behavior to only generate a single button from Gitlab MR name.
> fix(gitlab): Fix Gitlab MR showing two Toggl buttons

- src/scripts/content/bugherd.js
Replace all occurrences of < symbols
This was brought to my attention by Semmle's LGTM tool, which alerted me of the potentially incomplete escaping:
See: https://lgtm.com/projects/g/toggl/toggl-button/snapshot/1d7de0b6a430e9f0620ced1b35e8ffded70b8946/files/src/scripts/content/bugherd.js?sort=name&dir=ASC&mode=heatmap
> Bugherd: Replace all occurrences of < symbols

- src/scripts/content/redmine.js
Currently the button is rendered in the first `h2` tag found. Depending on installed plugins in Redmine there are multiple `h2` tags present. This leads to having the button rendered at the wrong position and using the wrong title.
This PR makes the selectors more specific by using `#content h2` to detect `numElem` and button position.
Use Redmine with Plugins installed. e.g. [Helpdesk](https://www.redmineup.com/pages/de/plugins/helpdesk)
> fix(redmine) Prevent positioning in sidebar

- src/scripts/origins.js
Adds the to-do.ofice.com url to the Microsoft to-do integration. Currently it only supports the personal version of todo, not the office 365 one. Added as a seperate option as it is possible someone may want to integrate with personal and not business etc.
> add to-do.ofice.com

- src/scripts/content/asana.js
- src/styles/style.css
It is visible on card item when you hover it. I decided to display it on the right because the size of button didn't really align well with items on the left:
Closes #1706
> Add integration for board layout

- src/scripts/common.js
Sets `data-no-focus-lock` attribute on form which prevents [this library](https://github.com/theKashey/focus-lock) to trap button's focus events
See #1704 it should work nicely now
Closes #1704
> fix(form): Add no focus lock attribute to form

- src/scripts/background.js
For now it only prints error from backend, which is descriptive enough, imho. We might actually add some actions pointing to ws settings, or something.
⚠️ All changes should be tested across Chrome and Firefox. ⚠️ 
* Set some constraints in ws settings
* Try to stop Time Entry in button without ☝️ fields filled in
*  There should be a notification 
Try pomodoro with "stop time entry" option set too
Closes #1430
> Add notification when trying to stop entry with unmet constraints

- src/scripts/background.js
When using "Discard and continue" option in the idle-detection notification, ensure that the tags from the running entry are copied to the new entry.
Prior to this PR, they did not get included if the "Automatic tagging" option was not enabled. The automatic tagging option is only describing the process of extracting tags/labels from within an integration, and should not affect the idle detection features.
This only affects Chrome, because this feature is not supported in Firefox.
Test locally:
1. "Idle detection" should be enabled,
2. "Enable automatic tagging" should be **disabled**
3. Apply this patch to speed up time. N.B. you should fully refresh the …
> Fix tags not being included when using discard + continue option

- src/scripts/content/visualstudio.js
Move Toggl Button form inside the azure task popup, so the project and tag dropdowns will open.
1. Open a task from board view (or [click here](https://dev.azure.com/togglbutton/Toggl%20Button%20Project/_boards/board/t/Toggl%20Button%20Project%20Team/Stories/?workitem=2))
2. Start timer
3. Open the project and tag dropdowns (which don't open on master)
Closes #1709
> chore(azure): Fix dropdowns on board view

- src/scripts/content/salesforce.js
- src/styles/style.css
I've moved the button to the "Utility bar" at the bottom of the page. It is not feasible to place it in the header anymore IMO, there are so many edge cases and the layout can't really be relied on in my experience. May need to review further in the future - or redo it from scratch with much more time spent on it.
We'll need to communicate with our friends in support that this will probably generate feedback / questions, since the button has moved.
More screenshots at the end of the PR showing what values it picks up.
Sorry, but you've got to give it a good thrashing. Things were breaking depending on what …
> fix(salesforce): Fix Salesforce Lightning buttons being temperemental

- src/scripts/content/todoist.js
1. Potential fix for some people not seeing buttons in the list-view under Todoist 1006. Also try to enhance project selection a little in general, since it doesn't work in some views.
2. Quick refactor on the "Task detail" integration to use the new data-attributes 🎉 . I propose that after we have a couple more examples and see how things go, we can then look to introducing a new render method (rather than writing the code for every integration using it).
It also happens to make the integration work on the Upcoming page 
I'm not entirely sure what broke since "it works on my machine", but I did find a consistent error …
> Fixes for Todoist version 1006

- src/scripts/content/gitlab.js
GitLab has it's own time tracking and block in sidebar, add the Toggl button there.
The major benefit is that the button is now at a fixed location, I do not have to scroll up on the page to find the button and start the tracker.
This also synchronizes with GitHub integration where the button is also at sidebar:
> Add additional toggl button to timetracking block

- src/scripts/content/workflowy.js
- src/styles/style.css
Fixes the workflowy integration by removing the old context menu functionality. It now uses a permanent minimal button attached to the header.
Here is what the integration looks like now:
When you click it it starts a timer for the bullet you last interacted with. If you haven't interacted with a bullet yet, it starts the timer for the top bullet on the page. You can also see the timer it will start when you hover over it:
1. Open workflowy.
2. Click the timer immediately.
3. Observe how it starts a "home" timer. (home is the name of the invisible top bullet)
1. Open Workflowy.
2. Create some bullets.
3. Click around on them.
4. Observe how the timer starts for …
> Move workflowy to minimal button

- src/scripts/content/todoist.js
- 3c60e97 - **fix(todoist): Fix duplicated button on todoist** 
For some reason there is an intermediary state when opening/closing the task's schedule popdown, where the `.toggl` class is removed and re-added.
This commit fixes it by checking if the toggl button is already present, before adding it.
- Check if everything looks fine on todoist integration 👌 
Related #1752
> fix(todoist): Fix duplicated button on todoist

- src/styles/autocomplete.css
Fixes issue where the "X tasks" label next to projects could vanish after you perform a search.
The latest layout for the projects + tasks uses `flex`, but the olden autocomplete CSS classes were overriding it to `block`. This broke the display of the task list label.
Change to specifically handle project rows and ensure they are flex.
See the linked case in the issue for a helpful video demonstrating the original problem
1. Search for a **client name**, where this client has a project with tasks assigned to it
2. You see the project filtered, and you can still see `X tasks` next to it _(this is the fix)_ …
> Fix tasks sometimes not showing in the Project dropdown when searching

- src/scripts/background.js
Truncates the time entry description in the Pomodoro "time's up" notification.
* With Pomodoro enabled and "stop timer at end" setting:
* The notification is shown, long entry is truncated
* if there's no description, the button should simply be `Continue Latest`
Other Pomodoro variations should not be affected.
Fixes #1746.
> Truncate long time entry descriptions in Pomodoro notification

- src/scripts/content/todoist.js
- src/styles/style.css
- Fixes button covering up long task names in the inbox when on far left
- Only show on hover in line with other todoist actions
- Removes old todoist list format
1. Create a todoist task with a very long name in the inbox
2. Button no longer covers up part of the task name
Closes #1758
> fix(todoist): Move list item button to far right and only visible on hover

- src/scripts/settings.js
Integrations sharing the same host could be shown as enabled even if they are not. (The prime case here being Google products).
The permission is requested on the full domain, but the list of origins in the UI would ignore the subdomains and show things as checked even if they aren't enabled. I think at one point this was a convenience feature for services that had many subdomains for the same app.. but it doesn't really hold up elsewhere.
I made a small tweak to the integration list to respect subdomain when creating the list of origins (`Settings.origins`)
* ⚠️ This integration origin list is 🍝  and we'll …
> Fix issues with integration checkboxes

- src/scripts/content/asana.js
- src/styles/colours.css
- Project names will be picked up again on the My Tasks page
- Move button to far right so they align if a project is present
1. Go to My Tasks page
2. Time a task with a project
3. Project is now picked up
4. Icons no longer do this
Closes #1757
> fix(asana): Update project selector for My Tasks page

- src/scripts/settings-theme.js
- src/scripts/settings.js
-  Replace event path usage with [element.closest](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest)
- `event.path` is not-standard, recommended standard is [event.composedPath()](https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath)
- But this usage can be simplified by using `element.closest(selector)`
- Open TB settings page
- Click the links in the sidebar under the `Settings` header they should work as expected
Closes #1776
> [Firefox] Fix settings navigation

- src/scripts/content/teamwork.js
There was a UI change in the Teamwork app. 
This PR fixes the integration.
The Toggl Button is visible at:
* Task list
* Single task view in side-view
* Single-page task view
Make sure it's visible and working in both browsers: 
Closes #1716
> fix(teamwork): Reposition Toggl Button after UI redesign

- src/scripts/content/toggl-plan.js
- src/styles/style.css
Fills in the description (from the Event name) and the project (from the Plan name, if available) fields in Toggl Plan TB integration.
* Open any Toggl Plan event
* Start a TB timer and check that the description matches the event description
* Make yourself a project that would match the plan name.
* Start a TB timer again and check that the project was automatically selected as well.
* If no project exists or a plan is not selected, the project field should be empty (no selection).
Closes #1793
> fix(toggl-plan): Extract Description & Project from the Plan event

- src/scripts/common.js
We've recently reworked button to use svg and we apparently forgot to hide `Start Timer` text from it.
In few integrations like Toggl Plan it worked by an accident but it screwed Trello checklist for example.
Check Trello checklists.
Before:
After:
Now matches our [style guide](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md#toggl-button-style-guide)
https://toggl.slack.com/archives/C9LMUPD9T/p1596045257219300
> fix(common): Hide text in minimal button type

- src/scripts/content/outlook.js
- src/styles/style.css
Only render one (not infinite) button in Outlook inbox/send email.
Go to outlook.live.com. Everything should work now 👏 
Closes #1800
> Fix Outlook integration

- src/styles/autocomplete.css
- Adds hover background to project list
- adds unique selector below to not interrupt other selectors.
- I tried adding light border as well; however, decided against it as I wanted to keep this simple and direct unless asked to do otherwise.
This was tested in Chrome and Firefox and works fine
To reproduce, open the toggle button, tap on a task, select to choose a project, move mouse over project list options.
Cursor would change, but no change to bg-color.
bg-color for project name changes to `var(--main-bg-color);` for consistency across themes.
issue #1813 requested this fix.
feat(dark-mode) #1769 was the original PR for adding dark-theme feature.
> fix(dark-mode): Dark-Mode project-list improved hover contrast

- src/styles/autocomplete.css
- src/styles/colours.css
- src/styles/popup.css
- Continuation of work from @devnetkc 
- Replace green/gray with rebrand pink/purple in the project/tag popdown
Related #1813
> Improve contrast for project/tag selection

- src/scripts/background.js
Improve Pomodoro timer sync when creating TEs on other apps/API. The Pomodoro timer should restart when getting new TEs from other services/API
- Turn on Pomodoro 
- I would suggest setting a small interval so you can see the animation better
- Start a new using the extension
- After a few minutes (before the Pomodoro ends) make an API call to start a new running TE.
- The extension should change the running TE to newly created one and set the Pomodoro state based on the current duration of the new TE. 
- If the new TE has a duration already bigger than the Pomodoro interval than the animation should go back to 0% and no alarm should trigger 
- Check if Pomodoro still working as expected when only using the extension 
- Updating the duration of TEs should also remove the timer if the new …
> fix(pomodoro): Improve pomdoro timer sync on new TEs

- README.md
- src/scripts/content/placker.js
- src/scripts/origins.js
- src/styles/style.css
- Added Toggl button to Placker card
Added a Toggl button to the card view in Placker. Automatically assigns the name of the card as the task and matches the board name to a project if one exists.
Open a board in Placker, double click a card to open card view, click the Placker button.
N/A
> add(Placker):Placker integration

- src/scripts/content/notion.js
Remove the Toggl Button prefix from the auto description when starting a new time entry
- Go to Notion
- Use the button next to the document title to start a new TE
- Description should not contain `Toggl Button`
close #1845
> fix(notion): Remove Toggl Button from default description

- src/scripts/common.js
Stop current time entry before starting a new one to avoid issues with time entry constraints
- Set some constraints to create time entries first
- Now go and create a new Time Entry using the button
- Try to start a new one without stopping the current one
- The first TE should stop and a new one should start 👍 
close #1846
> fix(timer): Stop current time entry before starting

- src/scripts/background.js
Stop using Pomodoro settings for TEs created outside the extension
- Start a TE in any other app
- Pomodoro settings should be ignored
- Start a TE using the extension
- Pomodoro settings ✔️ 
Bonus round:
Regression test on this issue https://github.com/toggl/toggl-button/issues/1801 
close #1857
> fix(pomodoro): Don't use pomodoro settings for non button TEs

- src/scripts/content/visualstudio.js
Move button to toolbar container to prevent it from sliding under the other buttons when the user shrinks the window.
Before:
After:
1. Create a MS account with your `@toggl` email
2. PM me for an invite to https://togglbuttontest.visualstudio.com/
3. Open any existing work item or issue
4. Shrink the window (make sure you can reproduce this with master too)
Closes #1866
> Fix button disappearing in Azure when user shrinks window

- src/scripts/origins.js
#1861 broke integrations that are starting with `www.` in origins.
This PR switches them to the wildcards and explicitly sets the `file` so that the scripts can be loaded properly on respective websites.
How about you be a good boy and test all 4 integrations? 😆 
Fixes what was broken by #1861
> Switch to wildcards instead of www

- src/scripts/content/asana.js
Fixes Asana integration's project selection bug.
Make sure you [read the comment](https://github.com/toggl/toggl-button/issues/1885#issuecomment-736602102) on the issue, for reasoning on the omission of the `[0]`.
Test with different combinations of projects and tasks in Asana.
Closes #1885
> fix(integrations): Fix Asana project selection

- src/scripts/content/toggl-plan.js
Plan has now their own integration with Track, so we must disable button if it's enabled on their side.
Just verify if it still injects properly on Plan. You can also create two elements (one with `data-track-inject-button` attr) and verify selector.
See: https://toggl.slack.com/archives/C0198AEAZ7T/p1605003706176300
> chore(toggl-plan): Use additional data-attr selector to inject

- .eslintrc.js
- src/scripts/common.js
This adds `$$` global selector do perform `document.querySelectorAll` simlarly to `$` being alias to `document.querySelector`
For example, this PR could take advantage of the shortcut: https://github.com/toggl/toggl-button/pull/1878
> Add $$ for querySelectorAll helper

- src/scripts/content/todoist.js
Fixes project field not populating on Todoist integration.
* First make sure there's a project in Todoist that has the same name as a Toggl project
Try two different things:
* Open the project page and create a task. See if starting a time entry based on that task populates the project by the same name. (this is the one that is fixed by this PR)
* Create a task in a project and schedule it for today. Then open the upcoming/today page and check whether starting a TE on that page will pick up the project name correctly (it's a different DOM). This used to work even before this PR and you need to verify that it still does.
Closes #1856
> fix(todoist): Fix todoist project population

- src/scripts/content/openproject.js
- src/styles/style.css
OpenProject 11.1 updated the work package detail page, removing the description heading that was previously used to show the toggl button. This PR moves the toggle button to the toolbar at the top of the work package page, keeping compatability with OP < 11.1, while also gaining compatability with future versions. I also think this generally is a better place for the button, as it is closer to where OP's built-in timetracking features are also presented.
https://github.com/opf/openproject/releases/tag/v11.1.0
> Updated for OpenProject 11.1

- src/scripts/content/atlassian.js
Make extension ready for new Issue View mode on Jira. The new feature will be fully released on March 31 but we already have some users using it so let's make it compatible 💪 
- Go to Jira
- `<domain>/secure/ViewPersonalSettings.jspa`
- Jira Labs, allow new Issue view mode
- Check if the button still showing 
- Go to Jira
- With the old view mode, check if the button still working
closes #1913
> fix(jira): Make button ready for new issue view

- src/scripts/content/atlassian.js
Fix Button not showing up when using the dialog view for Issues on Jira
So Jira has multiple ways to view the Issue:
- Single Page
- Dialog view on Kanban Board
- <domain>/secure/ViewPersonalSettings.jspa
- Jira Labs, allow new Issue view mode
- Open one Issue
- Check if the button still showing
- Go to Kanban board view
- Click on an Issue
- Check if the button will show up in the dialog
- Check if the button still getting all the information (Issue and Project)
- Go to Jira
- With the old view mode, check if the button still working
close #1913
> fix(jira): Fix button not showing on dialog view

- src/scripts/content/atlassian.js
- src/styles/style.css
Fix code to get the correct Issue number and Project not matter the view mode
All tests need to be done on Board view and Single page view
- Check if we get the issue number when an issue is part of an Epic
- Check if we get the project name when an issue is part of an Epic
- Check if we get the issue number correct no matter if part of a project or not
- Check if things are still working on old view mode, you can turn it on/off on "Personal Settings"
closes #1918
> fix(jira): Getting Issue and Project name from new view 

- src/scripts/content/youtrack.js
This PR fixes the task description when starting a task from youtrack's agile board. Currently the description layout is <code>A-1337 A-1337Task name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Toggl Button</code>, while it should be just `A-1337 Task name`.
All changes should be tested across Chrome and Firefox. As mentioned in #1797 it should be tested multiple times, since Toggle Track adds sometimes another (pre-PR conflicting) html container.
#1797
> fix(youtrack): Fix task description from agile board (closes #1797)

- src/scripts/content/asana.js
- src/styles/style.css
Fix description selector on task view (side view)
- Go to Asana
- Open one Task
- Check if the button is now showing up 👍 
- Check if is getting the description right
- Check if is getting the project and tags right
- Same as above but this time check the Board view
- https://github.com/toggl/toggl-button/issues/1916#issuecomment-781360362
- It should show the Toggl button on HOVER
close #1916
> fix(asana): Fix button not showing on task view

- src/scripts/common.js
Update button state when closing the form directly instead of waiting for focus event so we can avoid issues with other
event listeners from the page.
- Create a ZenDesk trial account
- After you're done, access an example ticket
- Now try to start new entries and check if the button state is always the expected when starting/stopping time entries.
close #1904
> fix(common): Update button state when closing the form

- package-lock.json
- package.json
- src/scripts/background.js
- src/scripts/components/LoginPage.tsx
- src/scripts/lib/bugsnag.ts
- src/scripts/lib/utils.ts
- src/scripts/popup.js
Treats most common Bugsnag errors.
* Upgrades Bugsnag library to `7.9.2`. Check https://github.com/bugsnag/bugsnag-js/blob/master/UPGRADING.md#6x-to-7x
* Adjusts path separators so errors are merged across OSs
* Omits common 403 error on getting user data (error `5f0ea96fe8175c001787b602`)
* Checks for element on addEventListener error (error `5dde294cb118e1001ae5a1d7`)
* Adds more debug info to URL error (error `6045ddaba7d01e001798e085`)
* Fixes Promised response from onMessage listener went out of scope (error `6045decb96760f0018a4d639`)
Helper docs on this one:
`onMessage `[should](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage#sending_an_asynchronous_response_using_a_promise) either return `true`, and then use `sendResponse`, OR it should …
> Bugsnag spring cleaning

- src/scripts/background.js
- src/scripts/common.js
Apparently those bugsnag errors are related to both `sync` and `stop-entry` messages, and this PR corrects both onMessage listeners per spec.
So... This should be covering:
* `5de0b5e4f79de300196e4f1b`
* `5b88010bab6255001a65abbf`
* `5ece29f9145cee0018b120c7`
* `6079720a12b7f10007ed979b`
And maybe
* `5f7de457f6ee25001783b977` (for erroring out when trying to fetch user data)
Closes #1942
> Treats Bugsnag error: Receiving end doesnt exist

- src/scripts/background.js
* Treats empty hostnames, so we don't get `"Invalid value for origin pattern *:///*: Host can not be empty."`
Possibly related bugsnag error: `5b88010bab6255001a65abbf`
> fix(bugsnag): Treat empty hostnames

- src/scripts/common.js
- src/scripts/content/bitrix24.js
- src/styles/style.css
Our selector doesn't work for elements within iframes.
This PRs adds this functionality, and updates the bitrix content script to make use of it.
Also, there was a missing closing braces on our styles, so I added that.
* Sign up for a bitrix account.
* Go to tasks and projects
* Click a task, it should open in an iframe, and have the toggl button
* Refresh the page. The task should open on the main document, and still have the button
Closes #1883
> Fix bitrix for iframes

- src/scripts/website-blocking/WebsiteBlocking.ts
> fix(siteBlock) Fix cannot read find of null for clean users

- src/html/settings.html
- src/scripts/background.js
- src/scripts/lib/db.js
- src/scripts/lib/utils.ts
- src/scripts/website-blocking/WebsiteBlocking.ts
- src/scripts/website-blocking/WebsiteBlockingApi.ts
- src/scripts/website-blocking/WebsiteBlockingConverter.ts
- src/scripts/website-blocking/WellKnownDistractions.ts
- src/scripts/website-blocking/predefined-websites.json
- src/scripts/website-blocking/ui/BlockingEnabledController.ts
- src/scripts/website-blocking/ui/CurrentlyBlockingListController.ts
- src/scripts/website-blocking/ui/ManuallyAddDistractionsController.ts
- src/scripts/website-blocking/ui/WellKnownDistractionsController.ts
- src/styles/settings.css
Adds displaying list of existing website blocking records with Delete buttons.
Adds a dropdown for selecting and blocking well-known distractos
Does some refactoring - we no longer use `JSON.stringify/parse` for storing the records data in db as it is totally fine with objects.
Complements error messages - how they list the URLs that are duplicated or already blocked
Add some records, remove some records.
Try to block websites from the well-known blockers dropdown. Make sure that dropdowns goes away when all records are blocked. Make sure it is refreshed when unblocking a well-known distractor
It might be incompatible with old data format - if something goes wrong, reset the settings to defaults.
> feat(siteBlock) Better UI/UX (existing records in lines) and some refactoring

- src/scripts/website-blocking/WebsiteBlocking.ts
The current implementation does block `https://www.instagram.com/`, but it fails to block `https://www.instagram.com/accounts/login/`.
The same is for `https://www.youtube.com` and direct links to videos like `https://www.youtube.com/watch?v=DYzXKZn_Z3w`.
Try opening `https://www.youtube.com/watch?v=DYzXKZn_Z3w` while blocking YT and tracking time.
> Fix blocking full URLs 

- package-lock.json
- package.json
- src/scripts/background.js
- src/scripts/lib/db.js
- src/scripts/lib/dbUtils.ts
- src/scripts/settings.js
For cases where serialised data of projects and clients exceeds 5 MB, the extension wouldn't log in.
This PR changes storing of projects and clients to IndexedDB thereby avoiding the given limitation and not introducing new required permissions like other storages do (`unlimitedStorage`).
Since IndexedDB API is verbose and we might make heavy use of it in the future, I took the liberty of introducing the `localforage` library to the extension. 
0) Generate a user with lots of projects and clients
1) Check if the current version of the extension can login. If it can, you probably don't have enough projects/clients.
2) Check if all pages work correctly - extension, settings, etc, and no issues in console. The `TrackExtension` object store (localforage database) should be available in …
> feat(db) Store projects, clients and other clientside data in IndexedDB to avoid LocalStorage limitation

- .travis.yml
Update Travis config to resolve warnings.
Check [this branch's  build](https://travis-ci.com/github/toggl/toggl-button/builds/233863887/config)
And previous [master build](https://travis-ci.com/github/toggl/toggl-button/builds/233862879/config) 
`skip_cleanup` is now [deprecated](https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release/#:~:text=skip_cleanup) and it's not cleaning up as default.
> chore(travis): Update config

- src/scripts/content/asana.js
Prevent multiple buttons on Asana's board view
1. Load the extension, enable Asana integration, and head to https://app.asana.com/
2. Sign in and head to the board view of some project, there should be a sample or just create one (and at least one task)
3. When you hover a task card on the board there should be a Toggl button next to the 👍 button
4. Clicking on a card on the board to show its details and closing the side pane doesn't add any more Toggl buttons to the card when you hover it again
closes #1958
> fix(asana): Prevent multiple buttons on board view

- src/scripts/content/microsoft-to-do.js
Fix the project selector for Microsoft To-Do
1. Go to MS To-Do and start a task from a list for which there's a project with the same name in the workspace (or create one)
2. The project field should be filled automatically
closes #1976
> fix(to-do): Fix project selector for MS To-Do

- src/scripts/lib/dbUtils.ts
Makes sure we "upgrade/initialize" the database before we try to interact with it.
Before this there could be a race condition where we try before we initialize, and then after this the upgrade callback never tries to run again, as the database is already on the same requested version. So whoever got to that state wouldn't be able to get out of it, only if uninstalling and reinstalling, to clear related IDB db, I believe.
I bumped the version number to make sure the upgrade code runs.
* Go to chrome://extensions and inspect background.js of the extension
* Go to the "Application" tab and delete the IndexedDB database for the extension
* Disable and re-enable the extension (sometimes this wasn't enough for me. But a `chrome://restart` always seemed to do the trick
* You'll notice console …
> fix(idb): Fix IDB initialization

- src/scripts/content/shortcut.js
- src/scripts/origins.js
- src/styles/style.css
Clubhouse have changed their name to Shortcut, and their domain to `shortcut.com`. This PR uses the old integration to add support for this new domain, skins the button to better match the website theme, and adds the ability to pulls the story id from the card.
I have tested this on both Firefox and Chrome. The button is accessible on a card in Shortcut.
[Clubhouse's name is now Shortcut](https://clubhouse.io/blog/clubhouse-changing-our-name-to-shortcut/)
> feat: Add support for Shortuct (previously Clubhouse)

- src/scripts/background.js
- src/scripts/lib/autocomplete.js
- src/styles/edit-form.css
- Improve visual focus outlines on the edit form
- Improve tab navigation behavior on the edit form
Open the edit form both from the "Start timer" button embedded on the website or from the extension's own page and navigate through it using keyboard only.
> Improve keyboard navigation

- src/scripts/content/anydo.js
Fix unavailable timer button after Any.do updated [#1799](https://github.com/toggl/toggl-button/issues/1799).
[Any.do Integration Missing Button #1799](https://github.com/toggl/toggl-button/issues/1799)
> fix(any.do): Add support for new Any.do UI

- src/scripts/content/github.js
This is my first PR in this repo, I read the Contributing.md but let me know if I missed anything!
The current plugin doesn't pass the issue or PR number on GitHub projects through to the toggl button on there. It looks like GitHub might have changed the class the plugin was using to select the element.
After the fix the numElem passes, for example below the `#1569` is now being passed:
Load the plugin in chrome and firefox, then go to a project page (e.g. [a project on this repo](https://github.com/toggl/toggl-button/projects/6)) and click a ticket and click the "Start Timer". It should now show the `numElem` being passed.
> fix(github): Fix projects page numElem not passing

- src/scripts/content/airtable.js
- src/styles/style.css
Fixes the broken selectors for Airtable, so that the Toggl Button appears in place.
1. Sign in to Airtable (we have test credentials)
2. Make sure the Toggl Button is visible:
https://github.com/toggl/toggl-button/issues/1849
> fix(Airtable): Fix showing Toggl Button in Airtable

- src/content/dixa.js
- src/origins.js
Adding Dixa integration.
[dixa.com](https://dixa.com) is a customer support platform. Support agents can answer conversations on phone, email, chat, and social media.
> feat(dixa): Implement Dixa integration

- src/content/xero.js
- src/origins.js
Fixes the broken selectors for Xero, so that Toggl Button appears in place.
1. Sign in to Xero (we have test credentials)
2. Make sure the Toggl Button is visible:
https://github.com/toggl/toggl-button/issues/1910
> fix(Xero): Fix showing Toggl Button in Xero

- src/origins.js
- 04b580f - **fix(gdocs): Fix naming of Google Docs/Sheets/Slides integration**
- Go to the integrations section on the Settings page, and check if the integration name now includes Docs, Sheets and Slides apps.
Closes #2040
> Fix naming of Google Docs/Sheets/Slides integration

- src/styles/style.css
Fixes taiga.io kanban view.
Both one-line and miltiple-line cards should look okayish now:
Sign in to taiga.io, create a Kanban project and two cards to the board, one with a long name and one with a short name. 
They should both look good, not like in the screenshots from the issue.
Closes https://github.com/toggl/track-extension/issues/1929
> fix(taiga): Fix taiga.io kanban view

- src/content/outlook.js
- 01d1539 - Fix Outlook integration
- Check if the button shows up correctly in Outlook. 👌 
Closes #2045
> fix(outlook): Fix Outlook integration

- src/content/teamwork.js
- src/origins.js
Teamwork Desk was no longer showing the Toggl as expected [from our documentation](https://github.com/toggl/track-extension/wiki/Where-can-I-find-the-Button%3F#teamwork-desk)
I've updated the CSS selector in a new version just like it was done before with previous versions,
Here is what it looks like now:
Closes #2015
> fix(teamwork): Update CSS selectors for teamwork Desk

- src/content/notion.js
The root cause of the issue was in missing `title` attribute on the button. The title is set during the TB initalization based on the description derived from the page content.
In Notion description is extracted from the page main section. There are cases where Toggl Button renders before the main section and it cannot get the description during the initialization. 
The same title is available in the breadcrumbs that are rendered along with the Toggl Button is the top bar. As a fallback, I added extracting the description from the breadcrumbs last text value.
Go to [this page](https://www.notion.so/toggl/Support-Team-2b9bb02020ed4efa891ec96d0cceafdb) and run the timer.
Once the popdown is hidden, the button text should be "Stop timer".
Closes …
> fix(notion): Add extracting description from breadcrumbs as a fallback

- src/content/zendesk.js
- src/origins.js
Prevent zendesk button from render in 2 different places
1. Go to Zendesk task view
2. Toggl button should appear only in the header
Closes #2111
> fix(zendesk): Toggl button showing in 2 different places

- src/content/asana.js
Fix asana bug, the problem was in the description selector, we were using the `aria-label` to get the description element, but it changes with the language.
- Go to asana
- My settings
- Display
- Change the language
- Check if the button stills showing up
Closes #2120 
Closes #2124
> fix(asana): Fix bug with language

- src/content/gitlab.js
Restore the button that has been gone for a while:
I was reported internally by our project manager to your project manager, but no action came out of it, even the issue I had to create myself half year later:
- https://github.com/toggl/track-extension/issues/2140
and yet no action to that either, so here's my attempt to do your job what we pay you.
Fixes https://github.com/toggl/track-extension/issues/2140
> [gitlab]: Fix selector for sidebar time-tracker class

- src/content/clickup.js
- [fix(clickup): Remove space between # and task id](https://github.com/toggl/track-extension/commit/8888542aa31dc5e5892438235985b31ddcb13357)
There's not really a way to test this since I can't reproduce, but by the user's complaint it should fix the issue.
Related #2170
> fix(clickup): Remove space between # and task id

- src/content/trello.js
- [fix(trello): Fix projects selector](https://github.com/toggl/track-extension/commit/8dca22f9daa8fd5930e6e3871b9b36fb57af9199)
- Go to Trello with the Track Extension enabled
- Click the button on a task, and the project should be selected (if there is a equivalent project on Toggl Track).
Closes #2202
> fix(trello): Fix projects selector

- src/origins.js
VisualStudio online planning suite is now named "Azure Devops", make it easier to find
> Add "Azure DevOps" to Azure

- src/content/zendesk.js
We are using the Zendesk UI from 2021. The Toggl integration is working, but only fetching the ticket number and not the name. But the title would be really helpful for us.
Currently Toggl is searching for an element with aria-label Subject. But this does not exist in the German version of Zendesk, as is named Betreff.
This PR fetches the language of Zendesk from the `<html>` node, reads the correct Label-Name from the translation array (which can be extended for other languages) and the reads the title.
You would need to test the Toggle integration in Zendesk with english and german language. Toggle schould add the ticket id and subject for tracking.
> Add support for non-english zendesk

- src/origins.js
-[fix(azure): Adds file to origins obj](https://github.com/toggl/track-extension/commit/0733525285ec701ca1955a3d77ef743e2f60478e)
We changed the name in the origins file, and since we didn't have the file field for this integration it ended up breaking the integration
- Check if the integration is working again
Closes #2212
> fix(azure): Adds file to origins obj

- src/styles/style.css
- Go to Trello and enable dark mode (only available in some accounts)
- The button's text should look 👌 
- Test it with other Trello's themes and it should also look 👌 
Closes #2201
> fix(trello): Fix button on dark mode

- src/content/gitea.js
This PR fixes the Gitea integration for newer versions for Gitea which have reformatted the issue page.
When debugging the original code, there are two problems:
- the issue id appears after the title not before it as the code expects
- HTMLCollection of tags does not support forEach
These changes have been made.
These are fixes for Gitea v1.18. I will test against the latest version v1.19 once we update.
#2209
> fix gitea selectors for v1.18

- src/content/shortcut.js
- [fix(shortcut): Fix timer not starting when there's no project](https://github.com/toggl/track-extension/commit/03383d21bd248482a3f44293e068c12e21b850c2)
- Check if it's now possible to start a timer on shortcut in a storie without project
Closes toggl/track-extension-core#618
> fix(shortcut): Fix timer not starting when there's no project

- src/content/google-calendar.js
- [fix(google-cal): Fix button removing the edit button](https://github.com/toggl/track-extension/commit/6292e7d4b83525f416082ce87a9227970d3cd64d)
-
- Check if now opening an event with the toggl button on it doesn't hide the google cal edit button
Closes toggl/track-extension-core#621
> fix(google-cal): Fix button removing the edit button

- src/content/zendesk.js
Zendesk's UI is a complete mess nowadays. This is another attempt to fix button rendering in Zendesk
I put the button into the button group to the top right corner of the ticket's container, right before the filter button.
> another attempt to fix button rendering in Zendesk

- src/content/trello.js
- src/origins.js
- src/styles/style.css
fixes trello card integration
1. Enable the Trello extension.
2. Open a task on the list.
3. Confirm the toggl button appears.
4. Click the start timer and check this function works smoothly.
5. Verify that the edit details pop-up is placed above the card every time.
7. Click "Done" on the pop-up and verify that the Trello card remains visible
after this action.
6. Repeat the steps multiple times to ensure consistency.
Closes: #2275
> fix(trello): adjust selectors and debounce interval, and tweak margins

- src/styles/style.css
Better align the Notion button.
Before:
After:
> [DO NOT MERGE] fix(notion): Button is slightly misaligned

- .github/workflows/create-release.yml
auto generate release notes similar to how we do in core [here](https://github.com/toggl/track-extension-core/blob/9ddb78875a008f1bfb378a893cfb49a244d12625/.github/workflows/pre-release.yml#L201)
try in new release and hope it works
> fix(action): generate release notes in release

- src/content/github.js
Fix Toggl button isn't visible on an issue popup: #2269
Toggl button should be visible on top of assignees section in a issue pop-up.
Steps to reproduce the behaviour:
1. Go to a GitHub project
2. Click on an issue and open a popup
Closes #2269
> fix(github): Fix Toggl button isn't visible on an issue popup

- src/content/notion.js
Fixing the following bug report.
If we fully open and I start the timer from a Notion page, it does grab the title. But if the page (database item) is opened in "side peek" mode, the timer does not grab the title.
We must get page titles both for full-opened and "side peek" pages.
Steps to reproduce the behavior:
Open a database item in "side peek"
Start tracking time
1. Open Notion page in "side peek" mode.
2. Press the Toggl Track "Start timer" button.
3. The Notion page title should be used as the description in the Toggl Track popup.
Closes #2260
> fix(notion): Fix Notion's page title grabbing when opened in "side peek" mode

- src/content/youtrack.js
- src/origins.js
Fix Toggl button disappeared after UI update: https://github.com/toggl/track-extension/issues/2265
The Toggl button should appear on the issue page.
I tested the fix on the public Jetbrains Youtrack: https://youtrack.jetbrains.com/issues
Closes https://github.com/toggl/track-extension/issues/2265
> fix(youtrack): Fix Toggl button disappeared after UI update

- src/content/linear.js
- src/origins.js
- src/styles/style.css
Add an integration with Linear (project management / issue tracking tool). This adds a toggl track button in the board view only, and inserts the issue title, project name (as project), and issue ID + labels (as tags), when the button is clicked.
Right now they don't have semantic markup which results in some pretty nasty selectors.
Debugging showed the expected tags were getting sent to the `togglbutton.createTimerLink` options, but the "Toggl tags" aren't getting selected in the time entry that gets started (even if those tags have already been created). Perhaps this is an issue with the Toggl extension itself?
I asked the Linear team to add some semantic classes, `data-*` attributes, or even `aria-` roles that could be used to construct less brittle selectors, so I'll update this PR …
> Add linear integration

- .github/workflows/update-origins.js
- src/content/_custom_SampleScript.js
- src/custom-scripts.js
- src/index.d.ts
- src/origins.js
Add support to include and export custom scripts
CS team would add scripts that can be assigned to any hostname from extension-core
> feat(integration): Add support to execute packaged custom scripts

- src/content/freedcamp.js
- src/origins.js
- src/styles/style.css
Since i couldnt push to origin PR i created this new branch 🙏🏼 
🌟 What does this PR do?
Adds [Freedcamp](https://freedcamp.com/) integration
🐛 Recommendations for testing
📝 Links to relevant issues or information
> feat: Freedcamp integration

- src/styles/style.css
Fix this case:
Observe that the button was hidden and only shows when hovering the list, but not the checkbox.
> fix(trello): Button was hidden on certain hover conditions

- src/content/evernote.js
Fix placement of Toggl link in UI.
Login to Evernote and open a page with any note.
The Toggl link should be positioned correctly.
Closes #2134
> fix(evernote): Fix placement of Toggl link in UI

- src/content/asana.js
updates project header selector, should fix the list view project tracking and add project tracking to board view
- open a project in list view
- make sure toggl account has a project with same name
- track some time with extension
- check that the correct project is assigned
- repeat for board view
Closes: #2293
> fix(asana.js): update project header selector and include it in board view

- src/content/ticktick.js
Fix TickTick adding extra xxxx at the start of the description: #2312
- Updated selector for task description element in TickTick integration.
The description of the Toggl timer entry should be without the extra "xxxx" in it.
Closes #2312
> fix(ticktick): Fix TickTick adding extra xxxx at the start of the description

- src/content/youtrack.js
- src/styles/style.css
Adding Toggl button integration to YouTrack Agile board issue modal: #2316
The Toggl button should appear on the YouTrack Agile board issue modal.
I tested the fix on the public Jetbrains Youtrack: https://youtrack.jetbrains.com/agiles/
Closes #2316
> feat(youtrack): Add Toggl button to YouTrack Agile board issue modal

- src/content/github.js
Updated GitHub integration issue description retrieval to include issue number in timer entry.
Steps to reproduce the behavior:
1. Go to a GitHub project;
2. Click on an issue;
3. Click on "Start timer".
Closes #2116
> fix(github): Add issue number to a timer entry in a GitHub project

- src/content/sentry.js
Fix Sentry integration not working: #2328
- Update timer description to use full page title (previous selectors no longer work).
- Extract project name from the page title instead of using the project select element.
- Fixed DOM element selection for appending the timer link.
A Toggl button should be available on the Sentry issue page.
Closes #2328
> fix(sentry): Fix Sentry integration not working

- src/content/drupal.js
Updated the Drupal integration to retrieve the issue title.
1. Log in [Drupal.org](https://www.drupal.org/);
2. Go to issue page (e.g. https://www.drupal.org/node/2920800);
3. Start Toggl timer;
4. The issue title should be used as the timer entry.
Closes #928
> fix(drupal): Fix title retrieval for Drupal.org integration

- src/content/helpscout.js
- src/origins.js
This PR fixes the helpscout integration as they changed the UI.
PS: @with-shrey i needed to add the header as the CI was complaining, please let me know if it's correct.
Ensure that on Helpscout you see the button on the top bar as the screenshot.
Link to [case here](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481310087222?view=List).
> fix: helpscout integrations

- src/content/hubspot.js
Make button available in contacts , deals, companies etc most of details pages 
Also in list pages
> fix(hubspot): Add toggl button to list view

- src/content/github.js
- src/content/notion.js
- src/content/onlyoffice.js
- src/content/trello.js
> feat(auto-tracker): Add auto tracking capability to extension

- src/origins.js
Map existing integrations to the new Microsoft `cloud.microsoft` domain.
Changes according to [this](https://learn.microsoft.com/en-us/microsoft-365/enterprise/cloud-microsoft-domain?view=o365-worldwide) blog post.
> fix(microsoft): Add new `cloud.microsoft` domains

- src/content/notion.js
Fix description parsing for notion 
in some reload scenarios description is picked up as empty 
Try it with auto tracker
> fix(notion): Fix description parsing

- src/content/notion.js
- src/content/trello.js
This PR improves the TogglButton render on Trello even in slow networks.
It does still happen sometimes that the button does not appear but only in very slow networks and with the 'Disable Cache' from the dev tools checked (which is not going to be the case 99% of the time).
Tested with network throttling at 3G speed.
Ensure that the button is working.
See the [slack thread here](https://toggl.slack.com/archives/C043ZPZQ2JC/p1727968520838579?thread_ts=1727280001.195159&cid=C043ZPZQ2JC).
> fix(trello): optimize render for slow networks

- src/content/github.js
This PR is adding the support for the new Github issue beta page.
> First commit is formatting applied.
1. Use this branch and link it to the extension.
2. Go to Github, on the issue page (if you have the beta view enabled) you should now see the button.
3. Ensure that the title and the issue number are present in the TE description.
4. Also, it should automatically connect the first project (if exists).
closes: https://github.com/toggl/track-extension/issues/2352
> feat(github): add support for new issues panel

- src/content/backlog.js
- src/origins.js
This PR adds the new origin used on backlog to fix the problem of the non appearing button.
1. Ensure that on backlog.com the integration will work on the single issue view.
See this [slack thread](https://toggl.slack.com/archives/C043ZPZQ2JC/p1732734194651059) here.
> fix(backlog): add new origin

- src/content/linear.js
This PR fixes the board view resolving issue on Linear.app
On the board view, the integration should be able to resolve correctly, title, projects and tasks.
See this [slack thread](https://toggl.slack.com/archives/C043ZPZQ2JC/p1731874812456549) here.
> fix(linear): make board view to resolve projects and tags again

- src/content/youtrack.js
This PR adds a fix for the YouTrack single page issue (which is not working).
> First commit is formatting.
1. Go to YouTrack
2. Open an issue
3. You should see the button (and optionally if there's a project the project will match).
> fix(youtrack): add correct selector

- src/content/shortcut.js
Currently, when clicking on the "start timer" button in shortcut, no title is set. This PR looks one div deeper to find the title of the story.
- open shortcut.com
- open a card
- click the "start time" button in the actions menu
- verify that the title of the story is automatically added as the title of the time entry.
> add extra parentNode

- src/content/asana.js
This PR aim to fix the problem our customer has using Asana integration.
The idea is to try to find another approach to do the same things, adding also some console.debug that could be useful in case for better approach.
I did it completely new from scratch this time dividing the 'MyTasks' page from the 'Projects' page, this way we can be sure that the logic will not get too much complex.
Ensure that on asana, you can start the timer from the button, and getting the project and the tags correctly both from any project view and my tasks view.
PS: You can enable debug level logging to see the data resolution …
> fix(asana): try another approach to fix customer problem

- src/origins.js
Map existing integrations to the Microsoft `office365` domain.
> fix(microsoft): Add new `office365.com` domains

- src/content/redbooth.js
- src/origins.js
This PR adds the missing button when opening tasks on right panel
1. Go to Dashboard>My Tasks and open a task
2. Toggl Track button should appear in the right panel
[Thread](https://toggl.slack.com/archives/C043ZPZQ2JC/p1738932609346419) 🧵
> fix(redbooth): Add button on right panel task drawer

- src/content/google-calendar.js
- src/origins.js
**Issue**
Users reported that the "Edit Time Entry" dialog was causing the event popup to close unexpectedly in the Google Calendar integration. Additionally, I discovered that the Toggl button integration was missing in the Google Calendar detail view.
**Cause**
- Google Calendar appears to have changed how it tracks clicks outside the event popup. This change affected our "Edit Time Entry" functionality, as the click on the time entry was propagating a `pointerdown` event, which closed the Google event popup.
- The Toggl button was not rendering in the detail view because the structure of the detail view in Google Calendar had changed.
**Solution**
- …
> fix(google-calendar): fix edit time entry event closing event popup and details selector

- src/content/linear.js
- src/styles/style.css
**Issue**
The Toggl integration button was not visible on Linear list view and issue details view.
**Cause**
There were two distinct issues:
- The UI on Linear list view was likely updated, causing our existing selector to no longer match the elements, making the button not appear.
- For the issue details view, there was no implementation at all to render the Toggl button.
**Solution**
- Fixed the selector for list view integration button to match the updated UI elements.
- Added implementation for issue details view to render the Toggl button in the sidebar.
**List View:**
- Go to Linear page
- Go to issue list
- Verify that there is a Toggl button in every …
> fix(linear): fix linear issues list button and add linear issue details view button

- src/content/asana.js
**Issue**
Integration button not visible for project list view due to incorrect CSS selector and elements not being immediately available in DOM.
**Solution**
- Fixed incorrect CSS selector for project list view elements
- Added proper null checks and guards for elements that may not be immediately available
Open asana integration
Go to project list view
https://github.com/toggl/track-extension-core/issues/1434
> fix(asana): project list view button

- src/content/trello.js
- src/content/youtrack.js
**Issue**
Toggl button integration broken for single issues view due to UI changes causing CSS selector failures.
**Solution**
Updated hardcoded selector .idLink__ee62 to flexible [class*="idLink__"] to handle UI variations.
- Enable Toggl extension integration
- Go to Youtrack single issue view
- Confirm that button is visible
> fix(youtrack): fix youtrack extension integration

- src/content/trello.js
**Issue**
Toggl integration buttons were being duplicated on Trello cards and checklist items.
**Cause**
The duplicate button checks were using inconsistent selectors:
Card buttons checked for `.toggl-button.trello`
Checklist items checked for `.checklist-item-menu .toggl-button`
This inconsistency allowed duplicate buttons to be created when the DOM structure changed or when the render function was called multiple times.
**Solution**
Standardized the duplicate button detection by using consistent CSS selectors across both card and checklist item integrations to properly identify existing Toggl buttons and prevent duplicates.
- Enable Trello integration
- Open trello
- Find a card with bigger description
- Scroll down
- Confirm that there is just one toggl buttoon
All changes should be …
> fix(trello): fix trello button integration duplication issue

- src/styles/style.css
**Issue**
Toggl timer button appears misaligned (higher) compared to other elements in GitLab's issue header bar
**Cause**
Timer button used default vertical alignment while GitLab interface uses vertical-align: middle via gl-align-middle class
**Solution**
Updated .toggl-button.gitlab CSS to use vertical-align: middle and added margin-left: 6px for proper spacing to match GitLab's design system
> fix(gitlab): fix gitlab integration button UI issue
